//! Deterministic synthetic disk fixtures, and the SAFE-007 interlock that
//! stands between a destructive test suite and anything it might write to.
//!
//! Two obligations shape this crate.
//!
//! **SAFE-001** permits automated tests to touch only disposable media: regular
//! files holding synthetic images, ephemeral virtual disks, loopback devices
//! inside an isolated environment, or physical devices a harness has explicitly
//! provisioned as destructive-test fixtures. Section 11.3 adds that fixtures are
//! generated by script and cached, and Section 16 forbids committing binary disk
//! images. So the images live in this crate as *code*, and the bytes are
//! reproduced on demand.
//!
//! **SAFE-007** requires three independent proofs before a destructive suite may
//! run, and says outright that one environment variable is not enough. That is
//! [`interlock`], and the property it is built around is that disposability is
//! *computed* from the target's own bytes rather than asserted by whoever asked.
//!
//! A third obligation was added after a project review. Section 11.7 fails a
//! work package that claims a requirement without linked evidence, and this
//! crate had been claiming several: each fixture recorded a rationale that no
//! test could see. [`evidence`] binds the two, so a fixture's purpose is
//! computed from its bytes and generation refuses to write one that has stopped
//! serving it.
//!
//! This crate performs no privileged operation, opens no device, and launches no
//! process. It writes files where it is told to and refuses everything else.

pub mod catalogue;
pub mod evidence;

/// Helpers shared between this crate's test modules.
#[cfg(test)]
mod test_support {
    use std::sync::atomic::{AtomicU64, Ordering};

    /// A number unique within this process.
    ///
    /// Combined with the process id it gives every sandbox directory a name no
    /// concurrent run can also choose. The previous fixed names meant two
    /// `cargo test` invocations of this crate deleted each other's fixture
    /// trees, in the suite that gates destructive execution.
    pub fn next_sandbox_id() -> u64 {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        NEXT.fetch_add(1, Ordering::Relaxed)
    }
}
pub mod interlock;
pub mod layout;
pub mod manifest;
pub mod prober;
pub mod signature;
