//! Fail-closed Slint 1.17.1 ahead-of-time compiler adapter.
//!
//! This module is shared by `build.rs` and its fixture test target. It invokes
//! the compiler library directly, never the `slint-compiler` executable, and it
//! generates Rust source only in memory until every syntax, diagnostic, import,
//! resource, style, and output-location check has passed.

use std::cell::RefCell;
use std::collections::{BTreeSet, HashMap};
use std::fmt;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::rc::Rc;

use i_slint_compiler::diagnostics::BuildDiagnostics;
use i_slint_compiler::generator::OutputFormat;
use i_slint_compiler::object_tree::{Document, recurse_elem_including_sub_components};
use i_slint_compiler::parser::{self, NodeOrToken, SyntaxKind, SyntaxNode, SyntaxToken};
use i_slint_compiler::{
    CompilerConfiguration, ComponentSelection, DefaultTranslationContext, EmbedResourcesKind,
};

use crate::slint_environment;

/// The sole generated filename permitted below Cargo's canonical `OUT_DIR`.
pub const GENERATED_RUST_FILENAME: &str = "partman_ui.rs";

/// Inputs to one compiler invocation.
#[derive(Clone, Copy, Debug)]
pub struct CompileRequest<'a> {
    /// Production or fixture root `.slint` file.
    pub root: &'a Path,
    /// Directory containing every ordinary application import.
    pub ui_root: &'a Path,
    /// The one generated token contract allowed outside `ui_root`.
    pub token_contract: &'a Path,
    /// Existing Cargo output directory that will contain the fixed result.
    pub output_directory: &'a Path,
}

/// Fully validated compiler output, still held in memory.
#[derive(Debug)]
pub struct CompiledUi {
    generated_rust: Vec<u8>,
    output_path: PathBuf,
    tracked_files: BTreeSet<PathBuf>,
    resource_files: BTreeSet<PathBuf>,
}

impl CompiledUi {
    /// Deterministic Rust source generated by the pinned compiler.
    #[must_use]
    pub fn generated_rust(&self) -> &[u8] {
        &self.generated_rust
    }

    /// Canonical fixed output path selected before compilation.
    #[must_use]
    pub fn output_path(&self) -> &Path {
        &self.output_path
    }

    /// Canonical root, imported source, and file-resource dependencies.
    #[must_use]
    pub fn tracked_files(&self) -> &BTreeSet<PathBuf> {
        &self.tracked_files
    }

    /// Canonical file resources discovered by the compiler.
    ///
    /// The current boundary rejects all resources, so successful production
    /// output always exposes an empty set. Keeping this surface explicit makes
    /// later resource-policy changes auditable.
    #[must_use]
    pub fn resource_files(&self) -> &BTreeSet<PathBuf> {
        &self.resource_files
    }
}

/// A forbidden language construct found before code generation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ForbiddenSyntax {
    /// Slint's translation macro (`@tr`).
    Translation,
    /// Slint's image URL macro (`@image-url`).
    ImageUrl,
    /// A file-only import, which Slint interprets as a custom-font import.
    FontImport,
    /// Direct access to the generated raw palette outside its generated file.
    RawGeneratedPalette,
    /// Slint's upstream palette singleton.
    UpstreamPalette,
    /// Slint's upstream style-metrics singleton.
    UpstreamStyleMetrics,
    /// The general-purpose standard widget library.
    StandardWidgets,
    /// A style-sensitive Slint builtin outside the generated wrapper contract.
    UngovernedStyleBuiltin,
    /// PartMan-authored display text embedded in application markup.
    EmbeddedDisplayString,
}

impl fmt::Display for ForbiddenSyntax {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Translation => "@tr translation",
            Self::ImageUrl => "@image-url resource",
            Self::FontImport => "custom-font import",
            Self::RawGeneratedPalette => "raw generated-palette access",
            Self::UpstreamPalette => "upstream Palette access",
            Self::UpstreamStyleMetrics => "upstream StyleMetrics access",
            Self::StandardWidgets => "standard widget import",
            Self::UngovernedStyleBuiltin => {
                "style-sensitive builtin outside the generated wrapper contract"
            }
            Self::EmbeddedDisplayString => "PartMan display string embedded in Slint markup",
        })
    }
}

/// Why the AOT boundary refused a source tree or output destination.
#[derive(Debug)]
pub enum AotError {
    /// Ambient state could alter compiler behavior.
    Environment(slint_environment::ForbiddenEnvironmentName),
    /// A filesystem operation failed.
    Io {
        /// Operation being attempted.
        operation: &'static str,
        /// Path involved in the operation.
        path: PathBuf,
        /// Operating-system error.
        source: io::Error,
    },
    /// A source or destination escaped its allowed canonical boundary.
    Boundary {
        /// Refused path.
        path: PathBuf,
        /// Boundary description.
        reason: &'static str,
    },
    /// A forbidden Slint construct was found.
    Policy {
        /// Source containing the construct.
        path: PathBuf,
        /// Rejected construct.
        syntax: ForbiddenSyntax,
    },
    /// The compiler emitted at least one warning, note, or error.
    Diagnostics(String),
    /// The compiler resolved a style other than the pinned Fluent style.
    Style(String),
    /// A compiler-sensitive property was not explicitly authored.
    ImplicitStyleBinding {
        /// PartMan-owned source containing the element.
        path: PathBuf,
        /// Slint builtin whose default would otherwise be injected.
        element: &'static str,
        /// Required explicit property.
        property: &'static str,
    },
    /// The compiler discovered a file or in-memory resource.
    Resources(Vec<String>),
    /// Loaded-file reporting disagreed with the controlled import callback.
    ImportAccounting {
        /// Canonical files opened by the callback.
        callback_files: BTreeSet<PathBuf>,
        /// Canonical non-builtin files reported by compiler diagnostics.
        diagnostic_files: BTreeSet<PathBuf>,
        /// Canonical non-builtin documents retained by the type loader.
        loader_documents: BTreeSet<PathBuf>,
        /// Canonical non-builtin files the type loader says must be watched.
        watched_files: BTreeSet<PathBuf>,
    },
    /// Rust code generation itself failed.
    Generation(io::Error),
}

impl fmt::Display for AotError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Environment(error) => error.fmt(formatter),
            Self::Io {
                operation,
                path,
                source,
            } => {
                write!(formatter, "cannot {operation} {}: {source}", path.display())
            }
            Self::Boundary { path, reason } => {
                write!(formatter, "path {} violates {reason}", path.display())
            }
            Self::Policy { path, syntax } => {
                write!(formatter, "{} contains forbidden {syntax}", path.display())
            }
            Self::Diagnostics(report) => {
                write!(formatter, "Slint compiler emitted diagnostics:\n{report}")
            }
            Self::Style(style) => write!(formatter, "Slint resolved unpinned style {style:?}"),
            Self::ImplicitStyleBinding {
                path,
                element,
                property,
            } => write!(
                formatter,
                "{} has {element} without an explicit {property} binding",
                path.display()
            ),
            Self::Resources(resources) => {
                write!(
                    formatter,
                    "Slint resources are forbidden: {}",
                    resources.join(", ")
                )
            }
            Self::ImportAccounting {
                callback_files,
                diagnostic_files,
                loader_documents,
                watched_files,
            } => write!(
                formatter,
                "Slint import accounting mismatch: callback={callback_files:?}, diagnostics={diagnostic_files:?}, documents={loader_documents:?}, watched={watched_files:?}"
            ),
            Self::Generation(source) => write!(formatter, "Slint Rust generation failed: {source}"),
        }
    }
}

impl std::error::Error for AotError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Environment(source) => Some(source),
            Self::Io { source, .. } | Self::Generation(source) => Some(source),
            Self::Boundary { .. }
            | Self::Policy { .. }
            | Self::Diagnostics(_)
            | Self::Style(_)
            | Self::ImplicitStyleBinding { .. }
            | Self::Resources(_)
            | Self::ImportAccounting { .. } => None,
        }
    }
}

/// Compile and validate a Slint source tree without touching the output file.
///
/// # Errors
///
/// Fails on ambient `SLINT_*` state, invalid paths, forbidden syntax, every
/// compiler diagnostic (including warnings), style drift, any resource, import
/// accounting drift, or generator failure.
pub fn compile_to_memory(request: CompileRequest<'_>) -> Result<CompiledUi, AotError> {
    slint_environment::guard_current_environment().map_err(AotError::Environment)?;

    let paths = CanonicalInputs::new(request)?;
    let output_path = fixed_output_path(request.output_directory)?;
    let mut diagnostics = BuildDiagnostics::default();
    let root_syntax = parser::parse_file(&paths.root, &mut diagnostics)
        .ok_or_else(|| AotError::Diagnostics(diagnostics.to_string_vec().join("\n")))?;
    reject_forbidden_syntax(&root_syntax, &paths.root, false)?;

    let import_state = Rc::new(RefCell::new(ImportState::default()));
    let callback = controlled_import_callback(paths.clone(), Rc::clone(&import_state));
    let configuration = pinned_configuration(callback)?;
    let (document, diagnostics, loader) = spin_on::spin_on(i_slint_compiler::compile_syntax_node(
        root_syntax,
        diagnostics,
        configuration,
    ));

    if let Some(error) = import_state.borrow_mut().policy_error.take() {
        return Err(error);
    }
    if !diagnostics.is_empty() {
        return Err(AotError::Diagnostics(diagnostics.diagnostics_as_string()));
    }
    if loader.resolved_style != "fluent" {
        return Err(AotError::Style(loader.resolved_style));
    }
    verify_explicit_style_bindings(&document, &paths.root)?;

    let (resource_files, resource_labels) = collect_resources(&document, &loader)?;
    if !resource_labels.is_empty() {
        return Err(AotError::Resources(resource_labels));
    }

    let diagnostic_files = canonical_non_builtin_paths(
        diagnostics.all_loaded_files.iter().cloned(),
        "canonicalize a diagnostics-reported import",
    )?;
    let loader_documents = canonical_non_builtin_paths(
        loader
            .all_file_documents()
            .map(|(path, _document)| path.clone()),
        "canonicalize a type-loader document",
    )?;
    let watched_files = canonical_non_builtin_paths(
        loader.all_files_to_watch(),
        "canonicalize a type-loader watched file",
    )?;
    let callback_imports = import_state.borrow().opened_files.clone();
    let mut expected_watched_files = callback_imports.clone();
    expected_watched_files.extend(resource_files.iter().cloned());
    if callback_imports != diagnostic_files
        || callback_imports != loader_documents
        || expected_watched_files != watched_files
    {
        return Err(AotError::ImportAccounting {
            callback_files: callback_imports,
            diagnostic_files,
            loader_documents,
            watched_files,
        });
    }

    // The Rust generator independently reads `SLINT_LIVE_PREVIEW`; keep the
    // fail-closed invariant local to that environment-reading call rather than
    // relying only on the earlier compiler-constructor guard.
    slint_environment::guard_current_environment().map_err(AotError::Environment)?;
    let mut generated_rust = Vec::new();
    i_slint_compiler::generator::generate(
        OutputFormat::Rust,
        &mut generated_rust,
        Some(&output_path),
        &document,
        &loader.compiler_config,
    )
    .map_err(AotError::Generation)?;

    let mut tracked_files = callback_imports;
    tracked_files.insert(paths.root);
    tracked_files.extend(resource_files.iter().cloned());

    Ok(CompiledUi {
        generated_rust,
        output_path,
        tracked_files,
        resource_files,
    })
}

/// Replace the one fixed generated file after successful in-memory validation.
///
/// Existing regular files are replaced; directories and symbolic links are
/// refused without mutation. The final creation uses `create_new` so a raced-in
/// destination cannot be overwritten.
///
/// # Errors
///
/// Returns [`AotError::Boundary`] for a non-regular existing destination and
/// [`AotError::Io`] for filesystem failures.
pub fn write_compiled_ui(compiled: &CompiledUi) -> Result<(), AotError> {
    match fs::symlink_metadata(&compiled.output_path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.file_type().is_file() {
                return Err(AotError::Boundary {
                    path: compiled.output_path.clone(),
                    reason: "the fixed output must be absent or an existing regular non-symlink file",
                });
            }
            fs::remove_file(&compiled.output_path).map_err(|source| AotError::Io {
                operation: "remove the prior generated file",
                path: compiled.output_path.clone(),
                source,
            })?;
        }
        Err(source) if source.kind() == io::ErrorKind::NotFound => {}
        Err(source) => {
            return Err(AotError::Io {
                operation: "inspect the generated-file destination",
                path: compiled.output_path.clone(),
                source,
            });
        }
    }

    let mut destination = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&compiled.output_path)
        .map_err(|source| AotError::Io {
            operation: "create the generated file exclusively",
            path: compiled.output_path.clone(),
            source,
        })?;
    destination
        .write_all(&compiled.generated_rust)
        .map_err(|source| AotError::Io {
            operation: "write the generated file",
            path: compiled.output_path.clone(),
            source,
        })
}

/// Compile, validate, and then write the fixed generated file.
///
/// # Errors
///
/// Propagates any compilation, policy, or output error from
/// [`compile_to_memory`] and [`write_compiled_ui`].
pub fn compile_and_write(request: CompileRequest<'_>) -> Result<CompiledUi, AotError> {
    let compiled = compile_to_memory(request)?;
    write_compiled_ui(&compiled)?;
    Ok(compiled)
}

#[derive(Clone, Debug)]
struct CanonicalInputs {
    root: PathBuf,
    ui_root: PathBuf,
    token_contract: PathBuf,
}

impl CanonicalInputs {
    fn new(request: CompileRequest<'_>) -> Result<Self, AotError> {
        let ui_root = canonical_directory(request.ui_root, "canonicalize the UI source root")?;
        let root = canonical_regular_file(request.root, "canonicalize the root Slint source")?;
        if !root.starts_with(&ui_root) {
            return Err(AotError::Boundary {
                path: root,
                reason: "the canonical UI source-root boundary",
            });
        }
        let token_contract = canonical_regular_file(
            request.token_contract,
            "canonicalize the generated token contract",
        )?;
        Ok(Self {
            root,
            ui_root,
            token_contract,
        })
    }

    fn allows_import(&self, path: &Path) -> bool {
        path.starts_with(&self.ui_root) || path == self.token_contract
    }
}

#[derive(Debug, Default)]
struct ImportState {
    opened_files: BTreeSet<PathBuf>,
    policy_error: Option<AotError>,
}

fn controlled_import_callback(
    paths: CanonicalInputs,
    state: Rc<RefCell<ImportState>>,
) -> i_slint_compiler::OpenImportCallback {
    Rc::new(move |requested| {
        let requested = PathBuf::from(requested);
        let result = load_controlled_import(&paths, &state, &requested);
        Box::pin(async move { Some(result) })
    })
}

fn load_controlled_import(
    paths: &CanonicalInputs,
    state: &Rc<RefCell<ImportState>>,
    requested: &Path,
) -> io::Result<String> {
    let canonical = match canonical_regular_file(requested, "canonicalize a Slint import") {
        Ok(path) => path,
        Err(error) => {
            state.borrow_mut().policy_error = Some(error);
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "import boundary refused path",
            ));
        }
    };
    if !paths.allows_import(&canonical) {
        state.borrow_mut().policy_error = Some(AotError::Boundary {
            path: canonical,
            reason: "the UI import root and exact generated-token exception",
        });
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "import escaped allowed roots",
        ));
    }

    let source = match fs::read_to_string(&canonical) {
        Ok(source) => source,
        Err(source) => {
            state.borrow_mut().policy_error = Some(AotError::Io {
                operation: "read a UTF-8 Slint import",
                path: canonical.clone(),
                source,
            });
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "import is not readable UTF-8",
            ));
        }
    };
    let mut policy_diagnostics = BuildDiagnostics::default();
    let syntax = parser::parse(source.clone(), Some(&canonical), &mut policy_diagnostics);
    if let Err(error) =
        reject_forbidden_syntax(&syntax, &canonical, canonical == paths.token_contract)
    {
        state.borrow_mut().policy_error = Some(error);
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "import syntax is forbidden",
        ));
    }

    state.borrow_mut().opened_files.insert(canonical);
    Ok(source)
}

fn reject_forbidden_syntax(
    syntax: &SyntaxNode,
    path: &Path,
    is_generated_token_contract: bool,
) -> Result<(), AotError> {
    for node in std::iter::once(syntax.clone()).chain(syntax.descendants()) {
        let forbidden = match node.kind() {
            SyntaxKind::AtTr => Some(ForbiddenSyntax::Translation),
            SyntaxKind::AtImageUrl => Some(ForbiddenSyntax::ImageUrl),
            SyntaxKind::ImportSpecifier
                if !node
                    .children()
                    .any(|child| child.kind() == SyntaxKind::ImportIdentifierList) =>
            {
                Some(ForbiddenSyntax::FontImport)
            }
            SyntaxKind::ImportSpecifier
                if node.text().to_string().contains("\"std-widgets.slint\"") =>
            {
                (!is_generated_token_contract || !is_approved_theme_import(&node))
                    .then_some(ForbiddenSyntax::StandardWidgets)
            }
            _ => None,
        };
        if let Some(syntax) = forbidden {
            return Err(AotError::Policy {
                path: path.to_path_buf(),
                syntax,
            });
        }
    }
    let mut palette_color_scheme_reads = 0;
    reject_forbidden_identifiers(
        syntax,
        path,
        is_generated_token_contract,
        &mut palette_color_scheme_reads,
    )?;
    if is_generated_token_contract && palette_color_scheme_reads != 2 {
        return Err(AotError::Policy {
            path: path.to_path_buf(),
            syntax: ForbiddenSyntax::UpstreamPalette,
        });
    }
    Ok(())
}

fn reject_forbidden_identifiers(
    node: &SyntaxNode,
    path: &Path,
    is_generated_token_contract: bool,
    palette_color_scheme_reads: &mut usize,
) -> Result<(), AotError> {
    for child in node.children_with_tokens() {
        match child {
            NodeOrToken::Node(child) => {
                reject_forbidden_identifiers(
                    &child,
                    path,
                    is_generated_token_contract,
                    palette_color_scheme_reads,
                )?;
            }
            NodeOrToken::Token(token) if token.kind() == SyntaxKind::Identifier => {
                let forbidden = match token.text() {
                    "PartmanRawGeneratedPalette" if !is_generated_token_contract => {
                        Some(ForbiddenSyntax::RawGeneratedPalette)
                    }
                    "Palette"
                        if is_generated_token_contract && is_palette_import_identifier(&token) =>
                    {
                        None
                    }
                    "Palette"
                        if is_generated_token_contract
                            && is_approved_palette_color_scheme_read(&token) =>
                    {
                        *palette_color_scheme_reads += 1;
                        None
                    }
                    "Palette" => Some(ForbiddenSyntax::UpstreamPalette),
                    "StyleMetrics" => Some(ForbiddenSyntax::UpstreamStyleMetrics),
                    "Window" | "Dialog" | "Text" | "StyledText" | "TextInput"
                        if !is_generated_token_contract =>
                    {
                        Some(ForbiddenSyntax::UngovernedStyleBuiltin)
                    }
                    _ => None,
                };
                if let Some(syntax) = forbidden {
                    return Err(AotError::Policy {
                        path: path.to_path_buf(),
                        syntax,
                    });
                }
            }
            NodeOrToken::Token(token)
                if token.kind() == SyntaxKind::StringLiteral
                    && !is_generated_token_contract
                    && !is_approved_application_string(&token) =>
            {
                return Err(AotError::Policy {
                    path: path.to_path_buf(),
                    syntax: ForbiddenSyntax::EmbeddedDisplayString,
                });
            }
            NodeOrToken::Token(_) => {}
        }
    }
    Ok(())
}

fn is_approved_application_string(token: &SyntaxToken) -> bool {
    let is_import = token
        .parent_ancestors()
        .any(|ancestor| ancestor.kind() == SyntaxKind::ImportSpecifier);
    is_import || matches!(token.text(), "\" \"" | "\"\\n\"")
}

fn is_approved_theme_import(node: &SyntaxNode) -> bool {
    let compact = node
        .text()
        .to_string()
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect::<String>();
    matches!(
        compact.as_str(),
        "import{Palette}from\"std-widgets.slint\";"
            | "{Palette}from\"std-widgets.slint\";"
            | "{Palette}from\"std-widgets.slint\""
    )
}

fn is_palette_import_identifier(token: &SyntaxToken) -> bool {
    token
        .parent_ancestors()
        .any(|ancestor| ancestor.kind() == SyntaxKind::ImportIdentifierList)
}

fn is_approved_palette_color_scheme_read(token: &SyntaxToken) -> bool {
    let in_adapter = token.parent_ancestors().any(|ancestor| {
        ancestor.kind() == SyntaxKind::Component
            && ancestor
                .text()
                .to_string()
                .contains("PartmanGeneratedThemeAdapter")
    });
    if !in_adapter {
        return false;
    }
    let Some(dot) = next_non_trivia_token(token.clone()) else {
        return false;
    };
    let Some(member) = next_non_trivia_token(dot.clone()) else {
        return false;
    };
    dot.kind() == SyntaxKind::Dot
        && member.kind() == SyntaxKind::Identifier
        && member.text() == "color-scheme"
}

fn next_non_trivia_token(mut token: SyntaxToken) -> Option<SyntaxToken> {
    loop {
        token = token.next_token()?;
        if !matches!(token.kind(), SyntaxKind::Whitespace | SyntaxKind::Comment) {
            return Some(token);
        }
    }
}

fn verify_explicit_style_bindings(document: &Document, root_path: &Path) -> Result<(), AotError> {
    let mut violation = None;
    for component in document.exported_roots() {
        if violation.is_some() {
            break;
        }
        recurse_elem_including_sub_components(&component, &(), &mut |element, ()| {
            if violation.is_some() {
                return;
            }
            let element = element.borrow();
            let type_name = element
                .builtin_type()
                .map(|builtin| builtin.name.clone())
                .or_else(|| {
                    element
                        .native_class()
                        .map(|native| native.class_name.clone())
                });
            let Some(type_name) = type_name else { return };
            let (name, required): (&'static str, &[&'static str]) = match type_name.as_str() {
                "Window" | "WindowItem" => ("Window", &["background", "default-font-family"]),
                "Dialog" => ("Dialog", &["background", "default-font-family"]),
                "Text" | "SimpleText" | "ComplexText" => (
                    "Text",
                    &[
                        "color",
                        "font-family",
                        "font-size",
                        "font-weight",
                        "font-italic",
                        "letter-spacing",
                        "wrap",
                        "overflow",
                        "horizontal-alignment",
                        "vertical-alignment",
                    ],
                ),
                "StyledText" | "StyledTextItem" => (
                    "StyledText",
                    &[
                        "default-color",
                        "default-font-family",
                        "default-font-size",
                        "horizontal-alignment",
                        "vertical-alignment",
                    ],
                ),
                "TextInput" => (
                    "TextInput",
                    &[
                        "color",
                        "selection-background-color",
                        "selection-foreground-color",
                        "text-cursor-width",
                        "font-family",
                        "font-size",
                        "font-weight",
                        "font-italic",
                        "letter-spacing",
                        "wrap",
                        "horizontal-alignment",
                        "vertical-alignment",
                    ],
                ),
                _ => return,
            };
            for property in required {
                let compiler_supplied = element
                    .bindings
                    .get(*property)
                    .is_some_and(|binding| binding.borrow().span.is_none());
                if compiler_supplied {
                    violation = Some(AotError::ImplicitStyleBinding {
                        path: root_path.to_path_buf(),
                        element: name,
                        property,
                    });
                    return;
                }
            }
        });
    }
    violation.map_or(Ok(()), Err)
}

/// Construct the fully explicit compiler configuration after re-checking the
/// ambient environment immediately before Slint's environment-reading constructor.
///
/// # Errors
///
/// Returns [`AotError::Environment`] if any governed compiler input is present.
pub(crate) fn pinned_configuration(
    import_callback: i_slint_compiler::OpenImportCallback,
) -> Result<CompilerConfiguration, AotError> {
    slint_environment::guard_current_environment().map_err(AotError::Environment)?;
    let mut configuration = CompilerConfiguration::new(OutputFormat::Rust);
    configuration.embed_resources = EmbedResourcesKind::EmbedAllResources;
    configuration.include_paths = Vec::new();
    configuration.library_paths = HashMap::new();
    configuration.style = Some("fluent".to_owned());
    configuration.open_import_callback = Some(import_callback);
    configuration.resource_url_mapper = None;
    configuration.inline_all_elements = false;
    configuration.const_scale_factor = None;
    configuration.accessibility = true;
    configuration.enable_experimental = false;
    configuration.translation_domain = None;
    configuration.default_translation_context = DefaultTranslationContext::ComponentName;
    configuration.no_native_menu = true;
    configuration.cpp_namespace = None;
    configuration.error_on_binding_loop_with_window_layout = true;
    configuration.debug_info = false;
    configuration.debug_hooks = None;
    configuration.components_to_generate = ComponentSelection::ExportedWindows;
    configuration.library_name = None;
    configuration.rust_module = None;
    Ok(configuration)
}

fn fixed_output_path(output_directory: &Path) -> Result<PathBuf, AotError> {
    let output_directory = canonical_directory(output_directory, "canonicalize Cargo OUT_DIR")?;
    let output_path = output_directory.join(GENERATED_RUST_FILENAME);
    if output_path.parent() != Some(output_directory.as_path()) {
        return Err(AotError::Boundary {
            path: output_path,
            reason: "the canonical Cargo OUT_DIR",
        });
    }
    Ok(output_path)
}

fn canonical_directory(path: &Path, operation: &'static str) -> Result<PathBuf, AotError> {
    let canonical = fs::canonicalize(path).map_err(|source| AotError::Io {
        operation,
        path: path.to_path_buf(),
        source,
    })?;
    let metadata = fs::metadata(&canonical).map_err(|source| AotError::Io {
        operation: "inspect a canonical directory",
        path: canonical.clone(),
        source,
    })?;
    if !metadata.is_dir() || !canonical.is_absolute() {
        return Err(AotError::Boundary {
            path: canonical,
            reason: "an existing absolute canonical directory",
        });
    }
    Ok(canonical)
}

fn canonical_regular_file(path: &Path, operation: &'static str) -> Result<PathBuf, AotError> {
    let original_metadata = fs::symlink_metadata(path).map_err(|source| AotError::Io {
        operation,
        path: path.to_path_buf(),
        source,
    })?;
    if original_metadata.file_type().is_symlink() || !original_metadata.file_type().is_file() {
        return Err(AotError::Boundary {
            path: path.to_path_buf(),
            reason: "an existing regular non-symlink source file",
        });
    }
    let canonical = fs::canonicalize(path).map_err(|source| AotError::Io {
        operation,
        path: path.to_path_buf(),
        source,
    })?;
    if !canonical.is_absolute() {
        return Err(AotError::Boundary {
            path: canonical,
            reason: "an absolute canonical source path",
        });
    }
    Ok(canonical)
}

fn canonical_non_builtin_paths(
    files: impl IntoIterator<Item = PathBuf>,
    operation: &'static str,
) -> Result<BTreeSet<PathBuf>, AotError> {
    files
        .into_iter()
        .filter(|path| !path.to_string_lossy().starts_with("builtin:"))
        .map(|path| canonical_regular_file(&path, operation))
        .collect()
}

fn collect_resources(
    document: &i_slint_compiler::object_tree::Document,
    loader: &i_slint_compiler::typeloader::TypeLoader,
) -> Result<(BTreeSet<PathBuf>, Vec<String>), AotError> {
    let mut files = BTreeSet::new();
    let mut labels = BTreeSet::new();
    for current_document in std::iter::once(document).chain(loader.all_documents()) {
        for resource in current_document.embedded_file_resources.borrow().iter() {
            if let Some(path) = &resource.path {
                let raw_path = Path::new(path.as_str());
                labels.insert(raw_path.display().to_string());
                if !path.starts_with("builtin:") {
                    files.insert(canonical_regular_file(
                        raw_path,
                        "canonicalize a compiler-reported resource",
                    )?);
                }
            } else {
                labels.insert("<in-memory-resource>".to_owned());
            }
        }
        for (font, _source) in &current_document.custom_fonts {
            labels.insert(format!("custom-font:{font}"));
        }
    }
    Ok((files, labels.into_iter().collect()))
}
