import type { WorkspacePreview } from "@partman/ui";

export const workspacePreview: WorkspacePreview = {
  sourceLabel: "Synthetic preview · zero device access",
  devices: [
    {
      id: "fixture-nvme",
      label: "System NVMe",
      path: "fixture://nvme-system",
      bus: "NVMe",
      sizeBytes: 1_000_204_886_016n,
      identity: "preview:nvme:001",
      health: "healthy",
      nodes: [
        {
          id: "nvme-efi",
          track: "layout",
          role: "entity.partition",
          label: "EFI",
          subtitle: "GUID partition · EFI System",
          sizeBytes: 272_629_760n,
          fraction: 0.04,
          facts: [
            { kind: "text", label: "Partition type", value: "EFI System" },
            { kind: "byteSize", label: "Start offset", bytes: 1_048_576n },
          ],
        },
        {
          id: "nvme-windows",
          track: "layout",
          role: "entity.partition",
          label: "Windows",
          subtitle: "GUID partition · Basic data",
          sizeBytes: 749_731_708_928n,
          fraction: 0.72,
          facts: [
            {
              kind: "text",
              label: "Partition type",
              value: "Microsoft Basic Data",
            },
            {
              kind: "byteSize",
              label: "Start offset",
              bytes: 273_678_336n,
            },
          ],
        },
        {
          id: "nvme-recovery",
          track: "layout",
          role: "entity.partition",
          label: "Recovery",
          subtitle: "GUID partition · Windows recovery",
          sizeBytes: 1_073_741_824n,
          fraction: 0.08,
          facts: [
            {
              kind: "text",
              label: "Partition type",
              value: "Windows Recovery",
            },
            { kind: "text", label: "Protected", value: "Yes" },
          ],
        },
        {
          id: "nvme-free",
          track: "layout",
          role: "entity.freeSpace",
          label: "Unallocated",
          subtitle: "Contiguous free extent",
          sizeBytes: 249_126_805_504n,
          fraction: 0.24,
          facts: [
            { kind: "byteSize", label: "Alignment", bytes: 1_048_576n },
            {
              kind: "text",
              label: "Availability",
              value: "Unallocated",
            },
          ],
        },
        {
          id: "nvme-encryption",
          track: "layers",
          role: "entity.encryption",
          label: "BitLocker",
          subtitle: "Encrypted layer · locked state simulated",
          sizeBytes: 749_731_708_928n,
          fraction: 0.34,
          facts: [
            { kind: "text", label: "Protection", value: "Enabled" },
            {
              kind: "text",
              label: "Unlock source",
              value: "Unavailable in preview",
            },
          ],
        },
        {
          id: "nvme-filesystem",
          track: "layers",
          role: "entity.filesystem",
          label: "NTFS",
          subtitle: "File system layer",
          sizeBytes: 749_731_708_928n,
          fraction: 0.33,
          facts: [
            { kind: "text", label: "File system", value: "NTFS" },
            { kind: "byteSize", label: "Cluster size", bytes: 4_096n },
          ],
        },
        {
          id: "nvme-mount",
          track: "layers",
          role: "entity.mount",
          label: "System mount",
          subtitle: "Mounted path association",
          sizeBytes: 749_731_708_928n,
          fraction: 0.33,
          facts: [
            { kind: "text", label: "Mount", value: "C:\\" },
            { kind: "text", label: "State", value: "Preview only" },
          ],
        },
      ],
    },
    {
      id: "fixture-usb",
      label: "External SSD",
      path: "fixture://usb-external",
      bus: "USB",
      sizeBytes: 500_107_862_016n,
      identity: "preview:usb:002",
      health: "unknown",
      nodes: [
        {
          id: "usb-partition",
          track: "layout",
          role: "entity.partition",
          label: "APFS store",
          subtitle: "GUID partition · Apple APFS",
          sizeBytes: 500_106_813_440n,
          fraction: 1,
          facts: [
            { kind: "text", label: "Partition type", value: "Apple APFS" },
            { kind: "byteSize", label: "Start offset", bytes: 1_048_576n },
          ],
        },
        {
          id: "usb-container",
          track: "layers",
          role: "entity.container",
          label: "APFS container",
          subtitle: "Container layer",
          sizeBytes: 500_106_813_440n,
          fraction: 0.34,
          facts: [
            { kind: "text", label: "Container role", value: "External" },
            { kind: "text", label: "Physical stores", value: "1" },
          ],
        },
        {
          id: "usb-volume",
          track: "layers",
          role: "entity.volume",
          label: "Archive",
          subtitle: "APFS volume",
          sizeBytes: 420_000_000_000n,
          fraction: 0.33,
          facts: [
            { kind: "text", label: "Volume role", value: "Data" },
            { kind: "text", label: "Quota", value: "None" },
          ],
        },
        {
          id: "usb-filesystem",
          track: "layers",
          role: "entity.filesystem",
          label: "APFS",
          subtitle: "File system layer",
          sizeBytes: 420_000_000_000n,
          fraction: 0.33,
          facts: [
            { kind: "text", label: "File system", value: "APFS" },
            { kind: "text", label: "Case sensitive", value: "No" },
          ],
        },
      ],
    },
  ],
  plan: {
    title: "Resize Windows and reserve dual-boot space",
    summary:
      "A presentation fixture showing how risk and ordering will appear after the planner exists.",
    severity: "severity.dataMoving",
    steps: [
      "Validate the current snapshot and identity",
      "Shrink the NTFS file system",
      "Shrink the containing partition",
      "Leave the resulting extent unallocated",
    ],
  },
};
