//! The registry's whole job in this increment is being empty and refusing,
//! so these tests pin the emptiness and exercise every refusal by name.
//!
//! The fake suite below is compiled only into tests. The shipped registry is
//! the empty `REGISTERED` constant, and `the_shipped_registry_is_empty` is
//! the reviewed edit-detector: the first real suite is increment 2h's
//! delivery, and landing it must flip that test visibly and re-open every
//! generic-refusal test for re-reading.

use std::fs;
use std::path::PathBuf;

use super::{
    Admission, FixtureContract, IntendedChange, Refusal, Suite, TargetClass, TeardownObligation,
    registered,
};
use crate::catalogue;
use crate::interlock::{Authorization, DESTRUCTIVE_PROFILE, Request, authorize};
use crate::manifest::Manifest;

/// A generated fixture tree in a unique temporary directory, mirroring the
/// interlock tests' sandbox for the same reason: admission consumes a real
/// `Authorization`, and a real authorization needs real generated bytes.
struct Sandbox {
    root: PathBuf,
    manifest: Manifest,
}

impl Sandbox {
    fn new(tag: &str) -> Self {
        let base =
            std::env::var_os("PARTMAN_TEST_ROOT").map_or_else(std::env::temp_dir, PathBuf::from);
        let root = base.components().collect::<PathBuf>().join(format!(
            "partman-registry-{tag}-{}-{}",
            std::process::id(),
            crate::test_support::next_sandbox_id()
        ));
        let _ = fs::remove_dir_all(&root);
        let manifest = catalogue::generate(&root).expect("generating fixtures must succeed");
        Self { root, manifest }
    }

    /// A passing authorization over exactly `names`.
    fn authorization(&self, names: &[&str]) -> Authorization {
        let request = Request {
            profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
            token: Some(self.manifest.token().to_owned()),
            targets: names.iter().map(|name| self.root.join(name)).collect(),
        };
        authorize(&self.root, &request).expect("all three factors are present")
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

/// 4 MiB, the generated length of every 512-byte-sector fixture used here.
const FIXTURE_LENGTH: u64 = 4 * 1024 * 1024;

static FAKE_RANGES: [IntendedChange; 1] = [IntendedChange {
    offset: 512,
    length: 8,
    reason: "the primary GPT header signature bytes, the smallest honest mutation",
}];

static FAKE_FIXTURES: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &FAKE_RANGES,
}];

/// The test-only suite. Never part of `REGISTERED`; a value here proves the
/// refusal semantics without registering anything in the shipped binary.
static FAKE_SUITE: Suite = Suite {
    name: "test-only-fake-suite",
    target_class: TargetClass::GeneratedFixtureFile,
    fixtures: &FAKE_FIXTURES,
    teardown: &[
        TeardownObligation::ChangedExactlyAsContracted,
        TeardownObligation::UnchangedOutsideContract,
        TeardownObligation::DetachConfirmed,
        TeardownObligation::BackingRegeneratedToCatalogue,
    ],
};

/// A suite equal to the fake one except for the fixture contracts.
fn suite_with(fixtures: &'static [FixtureContract]) -> Suite {
    Suite {
        name: "test-only-fake-suite",
        target_class: TargetClass::GeneratedFixtureFile,
        fixtures,
        teardown: FAKE_SUITE.teardown,
    }
}

// Malformed contracts, one per refusal gate. Module-scope statics because the
// contract types borrow `'static` data, and clippy's `items_after_statements`
// (workspace policy) forbids declaring them mid-test.

static NO_CHANGE: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &[],
}];

static ZERO: [IntendedChange; 1] = [IntendedChange {
    offset: 512,
    length: 0,
    reason: "a range that permits nothing",
}];
static ZERO_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &ZERO,
}];

static PAST_END: [IntendedChange; 1] = [IntendedChange {
    offset: FIXTURE_LENGTH - 4,
    length: 8,
    reason: "a range extending past the end",
}];
static PAST_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &PAST_END,
}];

static OVERFLOW: [IntendedChange; 1] = [IntendedChange {
    offset: u64::MAX,
    length: 2,
    reason: "an offset whose end overflows",
}];
static OVERFLOW_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &OVERFLOW,
}];

static OVERLAPPING: [IntendedChange; 2] = [
    IntendedChange {
        offset: 512,
        length: 8,
        reason: "first claim on byte 519",
    },
    IntendedChange {
        offset: 519,
        length: 8,
        reason: "second claim on byte 519",
    },
];
static OVERLAP_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &OVERLAPPING,
}];

static TOUCHING: [IntendedChange; 2] = [
    IntendedChange {
        offset: 512,
        length: 8,
        reason: "bytes 512..520",
    },
    IntendedChange {
        offset: 520,
        length: 8,
        reason: "bytes 520..528, sharing nothing",
    },
];
static TOUCHING_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &TOUCHING,
}];

static DUP: [FixtureContract; 2] = [
    FixtureContract {
        fixture: "gpt-basic-512.img",
        may_change: &FAKE_RANGES,
    },
    FixtureContract {
        fixture: "gpt-basic-512.img",
        may_change: &FAKE_RANGES,
    },
];

static GONE: [FixtureContract; 1] = [FixtureContract {
    fixture: "never-generated.img",
    may_change: &FAKE_RANGES,
}];

// Requirements: SAFE-007, SAFE-005
//   The shipped destructive-suite registry is empty, so no destructive suite exists to run; the first entry is a reviewed edit that re-opens every generic-refusal test.
// Evidence: the_shipped_registry_is_empty
#[test]
fn the_shipped_registry_is_empty() {
    assert!(
        registered().is_empty(),
        "the shipped registry gained a suite. That is increment 2h's delivery and it is \
         allowed to happen exactly once per recorded boundary — but every generic-refusal \
         test in this crate and in xtask changes meaning at this edit, and each must be \
         re-read, not merely re-run, before this assertion is updated"
    );
}

// Requirements: SAFE-007
//   A well-formed contract over an authorization carrying exactly the declared fixture set is admitted, and the admission carries the verified objects.
// Evidence: a_well_formed_suite_over_its_exact_target_set_is_admitted
#[test]
fn a_well_formed_suite_over_its_exact_target_set_is_admitted() {
    let sandbox = Sandbox::new("admit");
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let admission =
        Admission::admit(&FAKE_SUITE, authorization).expect("a well-formed suite is admitted");
    assert_eq!(admission.suite().name, "test-only-fake-suite");
    assert_eq!(admission.into_targets().len(), 1);
}

// Requirements: SAFE-007, SAFE-005
//   An authorization over a superset of the declared fixture set is refused: a suite may not receive an object its contract does not name.
// Evidence: an_undeclared_authorized_target_is_refused
#[test]
fn an_undeclared_authorized_target_is_refused() {
    let sandbox = Sandbox::new("extra");
    let authorization = sandbox.authorization(&["gpt-basic-512.img", "blank-512.img"]);
    let refusal =
        Admission::admit(&FAKE_SUITE, authorization).expect_err("an undeclared target must refuse");
    match refusal {
        Refusal::TargetsNotTheDeclaredSet { missing, extra, .. } => {
            assert!(missing.is_empty());
            assert_eq!(extra, ["blank-512.img"]);
        }
        other => panic!("wrong refusal: {other}"),
    }
}

// Requirements: SAFE-007, SAFE-005
//   An authorization missing a declared fixture is refused: the contract's digest bracket cannot be established over objects that are not there.
// Evidence: a_missing_declared_fixture_is_refused
#[test]
fn a_missing_declared_fixture_is_refused() {
    let sandbox = Sandbox::new("missing");
    let authorization = sandbox.authorization(&["blank-512.img"]);
    let refusal = Admission::admit(&FAKE_SUITE, authorization)
        .expect_err("a missing declared fixture must refuse");
    match refusal {
        Refusal::TargetsNotTheDeclaredSet { missing, extra, .. } => {
            assert_eq!(missing, ["gpt-basic-512.img"]);
            assert_eq!(extra, ["blank-512.img"]);
        }
        other => panic!("wrong refusal: {other}"),
    }
}

// Requirements: SAFE-007, SAFE-005
//   A suite declaring no fixtures is refused rather than vacuously admitted.
// Evidence: a_suite_addressing_nothing_is_refused
#[test]
fn a_suite_addressing_nothing_is_refused() {
    let sandbox = Sandbox::new("nothing");
    let suite = Box::leak(Box::new(suite_with(&[])));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an empty fixture set must refuse");
    assert_eq!(
        refusal,
        Refusal::SuiteAddressesNothing {
            suite: "test-only-fake-suite"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A contract permitting no change is refused: a suite that changes nothing must not carry the destructive profile.
// Evidence: a_contract_permitting_no_change_is_refused
#[test]
fn a_contract_permitting_no_change_is_refused() {
    let sandbox = Sandbox::new("nochange");
    let suite = Box::leak(Box::new(suite_with(&NO_CHANGE)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a vacuous contract must refuse");
    assert_eq!(
        refusal,
        Refusal::ContractPermitsNoChange {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A zero-length declared range is refused: it permits nothing and reads as if it permits something.
// Evidence: a_zero_length_range_is_refused
#[test]
fn a_zero_length_range_is_refused() {
    let sandbox = Sandbox::new("zerolen");
    let suite = Box::leak(Box::new(suite_with(&ZERO_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a zero-length range must refuse");
    assert_eq!(
        refusal,
        Refusal::EmptyRange {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img",
            offset: 512
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A range past the generated length is refused, including on addition overflow.
// Evidence: a_range_past_the_generated_length_is_refused
#[test]
fn a_range_past_the_generated_length_is_refused() {
    let sandbox = Sandbox::new("oob");
    let suite = Box::leak(Box::new(suite_with(&PAST_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an out-of-bounds range must refuse");
    assert!(matches!(refusal, Refusal::RangeOutOfBounds { .. }));

    // The overflow shape refuses the same way rather than wrapping.
    let overflow_suite = Box::leak(Box::new(suite_with(&OVERFLOW_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal = Admission::admit(overflow_suite, authorization)
        .expect_err("an overflowing range must refuse");
    assert!(matches!(refusal, Refusal::RangeOutOfBounds { .. }));
}

// Requirements: SAFE-007, SAFE-005
//   Overlapping declared ranges are refused; touching ranges are not, and the boundary byte is the test.
// Evidence: overlapping_ranges_are_refused_and_touching_ranges_are_not
#[test]
fn overlapping_ranges_are_refused_and_touching_ranges_are_not() {
    let sandbox = Sandbox::new("overlap");
    let suite = Box::leak(Box::new(suite_with(&OVERLAP_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("overlapping ranges must refuse");
    assert_eq!(
        refusal,
        Refusal::RangesOverlap {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );

    let touching_suite = Box::leak(Box::new(suite_with(&TOUCHING_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    Admission::admit(touching_suite, authorization).expect("touching ranges are admitted");
}

// Requirements: SAFE-007, SAFE-005
//   A duplicate fixture contract is refused as ambiguous.
// Evidence: a_duplicate_fixture_contract_is_refused
#[test]
fn a_duplicate_fixture_contract_is_refused() {
    let sandbox = Sandbox::new("dup");
    let suite = Box::leak(Box::new(suite_with(&DUP)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a duplicate contract must refuse");
    assert_eq!(
        refusal,
        Refusal::DuplicateFixtureContract {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A contract naming a fixture the catalogue does not generate is refused, so a contract cannot outlive its fixture.
// Evidence: a_contract_over_a_withdrawn_fixture_is_refused
#[test]
fn a_contract_over_a_withdrawn_fixture_is_refused() {
    let sandbox = Sandbox::new("withdrawn");
    let suite = Box::leak(Box::new(suite_with(&GONE)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an unknown fixture must refuse");
    assert_eq!(
        refusal,
        Refusal::NotAGeneratedFixture {
            suite: "test-only-fake-suite",
            fixture: "never-generated.img"
        }
    );
}

// Requirements: SAFE-007
//   Admission is unreachable without every interlock factor: its signature consumes the authorization the factors produce, so a missing factor refuses upstream and no admission can exist.
// Evidence: a_suite_cannot_be_admitted_without_every_interlock_factor
#[test]
fn a_suite_cannot_be_admitted_without_every_interlock_factor() {
    // The registry adds a condition; it must never substitute for one. The
    // only constructor consumes an `Authorization`, so the demonstration is
    // that the authorization itself refuses — there is no admission code
    // path that could run after this, by type rather than by discipline.
    let sandbox = Sandbox::new("factors");
    let request = Request {
        profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
        token: None,
        targets: vec![sandbox.root.join("gpt-basic-512.img")],
    };
    authorize(&sandbox.root, &request).expect_err("a missing token must refuse upstream");
}

// Requirements: SAFE-007
//   The target-class and teardown vocabularies are closed: an exhaustive match pins every variant, so a new one fails compilation here as a visible reviewed edit.
// Evidence: the_registry_vocabularies_are_closed
#[test]
fn the_registry_vocabularies_are_closed() {
    // No wildcard arms. Adding a variant to either enum breaks this build
    // until the addition is reviewed here, which is the point.
    fn name_class(class: TargetClass) -> &'static str {
        match class {
            TargetClass::GeneratedFixtureFile => "generated-fixture-file",
        }
    }
    fn name_obligation(obligation: TeardownObligation) -> &'static str {
        match obligation {
            TeardownObligation::ChangedExactlyAsContracted => "changed-exactly-as-contracted",
            TeardownObligation::UnchangedOutsideContract => "unchanged-outside-contract",
            TeardownObligation::DetachConfirmed => "detach-confirmed",
            TeardownObligation::BackingRegeneratedToCatalogue => "backing-regenerated-to-catalogue",
        }
    }
    assert_eq!(
        name_class(FAKE_SUITE.target_class),
        "generated-fixture-file"
    );
    assert_eq!(FAKE_SUITE.teardown.len(), 4);
    for obligation in FAKE_SUITE.teardown {
        assert!(!name_obligation(*obligation).is_empty());
    }
}
