//! The registry's job is admitting one exact shape and refusing everything
//! else, so these tests pin the shipped registry and exercise every refusal
//! by name.
//!
//! The fake suite below is compiled only into tests and is deliberately not
//! registered — which is also what lets it stand in for the "not registered"
//! case the executor refuses. `the_shipped_registry_holds_exactly_the_2h_suite`
//! is the reviewed edit-detector: it began life as `the_shipped_registry_is_empty`
//! under increment 2g and fired when 2h registered the first suite, which is
//! the moment every generic-refusal test was re-read.

use std::fs;
use std::path::PathBuf;

use super::{
    Admission, FixtureContract, IntendedChange, Refusal, Suite, TargetClass, TeardownObligation,
    registered,
};
use crate::catalogue;
use crate::interlock::{Authorization, DESTRUCTIVE_PROFILE, Request, authorize};
use crate::manifest::Manifest;

/// A generated fixture tree in a unique temporary directory, mirroring the
/// interlock tests' sandbox for the same reason: admission consumes a real
/// `Authorization`, and a real authorization needs real generated bytes.
struct Sandbox {
    root: PathBuf,
    manifest: Manifest,
}

impl Sandbox {
    fn new(tag: &str) -> Self {
        let base =
            std::env::var_os("PARTMAN_TEST_ROOT").map_or_else(std::env::temp_dir, PathBuf::from);
        let root = base.components().collect::<PathBuf>().join(format!(
            "partman-registry-{tag}-{}-{}",
            std::process::id(),
            crate::test_support::next_sandbox_id()
        ));
        let _ = fs::remove_dir_all(&root);
        let manifest = catalogue::generate(&root).expect("generating fixtures must succeed");
        Self { root, manifest }
    }

    /// A passing authorization over exactly `names`.
    fn authorization(&self, names: &[&str]) -> Authorization {
        let request = Request {
            profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
            token: Some(self.manifest.token().to_owned()),
            targets: names.iter().map(|name| self.root.join(name)).collect(),
        };
        authorize(&self.root, &request).expect("all three factors are present")
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

/// 4 MiB, the generated length of every 512-byte-sector fixture used here.
const FIXTURE_LENGTH: u64 = 4 * 1024 * 1024;

static FAKE_REPLACEMENT: [u8; 8] = [0xAA; 8];
static TWO_BYTES: [u8; 2] = [0xAA; 2];

static FAKE_RANGES: [IntendedChange; 1] = [IntendedChange {
    offset: 512,
    length: 8,
    replacement: &FAKE_REPLACEMENT,
    reason: "the primary GPT header signature bytes, the smallest honest mutation",
}];

static FAKE_FIXTURES: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &FAKE_RANGES,
}];

/// The test-only suite. Never part of `REGISTERED`; a value here proves the
/// refusal semantics without registering anything in the shipped binary.
static FAKE_SUITE: Suite = Suite {
    name: "test-only-fake-suite",
    target_class: TargetClass::GeneratedFixtureFile,
    fixtures: &FAKE_FIXTURES,
    teardown: &[
        TeardownObligation::ChangedExactlyAsContracted,
        TeardownObligation::UnchangedOutsideContract,
        TeardownObligation::DetachConfirmed,
        TeardownObligation::BackingRegeneratedToCatalogue,
    ],
};

/// A suite equal to the fake one except for the fixture contracts.
fn suite_with(fixtures: &'static [FixtureContract]) -> Suite {
    Suite {
        name: "test-only-fake-suite",
        target_class: TargetClass::GeneratedFixtureFile,
        fixtures,
        teardown: FAKE_SUITE.teardown,
    }
}

// Malformed contracts, one per refusal gate. Module-scope statics because the
// contract types borrow `'static` data, and clippy's `items_after_statements`
// (workspace policy) forbids declaring them mid-test.

static NO_CHANGE: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &[],
}];

static ZERO: [IntendedChange; 1] = [IntendedChange {
    offset: 512,
    length: 0,
    replacement: &[],
    reason: "a range that permits nothing",
}];

static MISMATCHED: [IntendedChange; 1] = [IntendedChange {
    offset: 512,
    length: 8,
    replacement: &TWO_BYTES,
    reason: "a range whose replacement cannot fill it",
}];
static MISMATCHED_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &MISMATCHED,
}];
static ZERO_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &ZERO,
}];

static PAST_END: [IntendedChange; 1] = [IntendedChange {
    offset: FIXTURE_LENGTH - 4,
    length: 8,
    replacement: &FAKE_REPLACEMENT,
    reason: "a range extending past the end",
}];
static PAST_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &PAST_END,
}];

static OVERFLOW: [IntendedChange; 1] = [IntendedChange {
    offset: u64::MAX,
    length: 2,
    replacement: &TWO_BYTES,
    reason: "an offset whose end overflows",
}];
static OVERFLOW_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &OVERFLOW,
}];

static OVERLAPPING: [IntendedChange; 2] = [
    IntendedChange {
        offset: 512,
        length: 8,
        replacement: &FAKE_REPLACEMENT,
        reason: "first claim on byte 519",
    },
    IntendedChange {
        offset: 519,
        length: 8,
        replacement: &FAKE_REPLACEMENT,
        reason: "second claim on byte 519",
    },
];
static OVERLAP_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &OVERLAPPING,
}];

static TOUCHING: [IntendedChange; 2] = [
    IntendedChange {
        offset: 512,
        length: 8,
        replacement: &FAKE_REPLACEMENT,
        reason: "bytes 512..520",
    },
    IntendedChange {
        offset: 520,
        length: 8,
        replacement: &FAKE_REPLACEMENT,
        reason: "bytes 520..528, sharing nothing",
    },
];
static TOUCHING_CONTRACT: [FixtureContract; 1] = [FixtureContract {
    fixture: "gpt-basic-512.img",
    may_change: &TOUCHING,
}];

static DUP: [FixtureContract; 2] = [
    FixtureContract {
        fixture: "gpt-basic-512.img",
        may_change: &FAKE_RANGES,
    },
    FixtureContract {
        fixture: "gpt-basic-512.img",
        may_change: &FAKE_RANGES,
    },
];

static GONE: [FixtureContract; 1] = [FixtureContract {
    fixture: "never-generated.img",
    may_change: &FAKE_RANGES,
}];

// Requirements: SAFE-007, SAFE-005
//   The shipped registry holds exactly the increment 2h single-range suite and the increment 2j two-range suite, whole shapes pinned; a further entry is a new reviewed edit that re-opens every generic-refusal test.
// Evidence: the_shipped_registry_holds_exactly_the_2h_and_2j_suites
#[test]
fn the_shipped_registry_holds_exactly_the_2h_and_2j_suites() {
    // This test was `the_shipped_registry_is_empty` until increment 2h made
    // the one edit 2g reserved, and pinned exactly the 2h suite until
    // increment 2j registered the two-range shape under its own boundary.
    // It fired at both edits — which is the moment every generic-refusal
    // test in this crate and in xtask is re-read, per the recorded
    // boundaries; the next entry re-opens them all again — so this pins the
    // whole shapes rather than a count.
    let suites = registered();
    assert_eq!(suites.len(), 2, "a further suite needs its own boundary");

    let suite = &suites[0];
    assert_eq!(suite.name, "gpt-basic-512-signature-erase");
    assert_eq!(suite.target_class, TargetClass::GeneratedFixtureFile);
    assert_eq!(suite.fixtures.len(), 1);
    let contract = &suite.fixtures[0];
    assert_eq!(contract.fixture, "gpt-basic-512.img");
    assert_eq!(contract.may_change.len(), 1);
    let range = &contract.may_change[0];
    assert_eq!(range.offset, 512);
    assert_eq!(range.length, 8);
    assert_eq!(range.replacement, [0_u8; 8]);
    assert_eq!(
        suite.teardown,
        [
            TeardownObligation::ChangedExactlyAsContracted,
            TeardownObligation::UnchangedOutsideContract,
            TeardownObligation::DetachConfirmed,
            TeardownObligation::BackingRegeneratedToCatalogue,
        ]
    );

    let suite = &suites[1];
    assert_eq!(suite.name, "gpt-basic-512-both-signatures-erase");
    assert_eq!(suite.target_class, TargetClass::GeneratedFixtureFile);
    assert_eq!(suite.fixtures.len(), 1);
    let contract = &suite.fixtures[0];
    assert_eq!(contract.fixture, "gpt-basic-512.img");
    assert_eq!(contract.may_change.len(), 2);
    let primary = &contract.may_change[0];
    assert_eq!(primary.offset, 512);
    assert_eq!(primary.length, 8);
    assert_eq!(primary.replacement, [0_u8; 8]);
    let backup = &contract.may_change[1];
    // 4 MiB minus one 512-byte sector: the backup GPT header's LBA. The
    // admission gate separately re-checks this against the compiled
    // generated length, so a resized fixture refuses the contract.
    assert_eq!(backup.offset, 4 * 1024 * 1024 - 512);
    assert_eq!(backup.length, 8);
    assert_eq!(backup.replacement, [0_u8; 8]);
    assert_eq!(
        suite.teardown,
        [
            TeardownObligation::ChangedExactlyAsContracted,
            TeardownObligation::UnchangedOutsideContract,
            TeardownObligation::DetachConfirmed,
            TeardownObligation::BackingRegeneratedToCatalogue,
        ]
    );
}

// Requirements: SAFE-007
//   Every registered suite's own contract is admitted over its declared set, so its well-formedness is executed rather than assumed.
// Evidence: the_registered_suites_are_admitted_over_their_declared_sets
#[test]
fn the_registered_suites_are_admitted_over_their_declared_sets() {
    for suite in registered() {
        let sandbox = Sandbox::new("registered");
        let names: Vec<&str> = suite
            .fixtures
            .iter()
            .map(|contract| contract.fixture)
            .collect();
        let authorization = sandbox.authorization(&names);
        let admission = Admission::admit(suite, authorization)
            .expect("a shipped suite must admit over exactly its declared fixtures");
        assert_eq!(admission.suite().name, suite.name);
    }
}

// Requirements: SAFE-007, SAFE-005
//   A replacement whose byte count differs from its range's length is refused: the contracted change would be unstatable.
// Evidence: a_replacement_length_mismatch_is_refused
#[test]
fn a_replacement_length_mismatch_is_refused() {
    let sandbox = Sandbox::new("mismatch");
    let suite = Box::leak(Box::new(suite_with(&MISMATCHED_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a mismatched replacement must refuse");
    assert_eq!(
        refusal,
        Refusal::ReplacementLengthMismatch {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img",
            offset: 512
        }
    );
}

// Requirements: SAFE-007
//   A well-formed contract over an authorization carrying exactly the declared fixture set is admitted, and the admission carries the verified objects.
// Evidence: a_well_formed_suite_over_its_exact_target_set_is_admitted
#[test]
fn a_well_formed_suite_over_its_exact_target_set_is_admitted() {
    let sandbox = Sandbox::new("admit");
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let admission =
        Admission::admit(&FAKE_SUITE, authorization).expect("a well-formed suite is admitted");
    assert_eq!(admission.suite().name, "test-only-fake-suite");
    assert_eq!(admission.into_targets().len(), 1);
}

// Requirements: SAFE-007, SAFE-005
//   An authorization over a superset of the declared fixture set is refused: a suite may not receive an object its contract does not name.
// Evidence: an_undeclared_authorized_target_is_refused
#[test]
fn an_undeclared_authorized_target_is_refused() {
    let sandbox = Sandbox::new("extra");
    let authorization = sandbox.authorization(&["gpt-basic-512.img", "blank-512.img"]);
    let refusal =
        Admission::admit(&FAKE_SUITE, authorization).expect_err("an undeclared target must refuse");
    match refusal {
        Refusal::TargetsNotTheDeclaredSet { missing, extra, .. } => {
            assert!(missing.is_empty());
            assert_eq!(extra, ["blank-512.img"]);
        }
        other => panic!("wrong refusal: {other}"),
    }
}

// Requirements: SAFE-007, SAFE-005
//   Several verified handles for one declared fixture are refused at admission: the contract binds one object per fixture, and a name-set comparison cannot count.
// Evidence: duplicate_verified_handles_for_one_fixture_are_refused
#[cfg(unix)]
#[test]
fn duplicate_verified_handles_for_one_fixture_are_refused() {
    let sandbox = Sandbox::new("duphandles");
    // Two spellings of one file survive the interlock's supplied-path dedup
    // and verify into two handles to one object. The spelling matters:
    // `Path` equality normalizes `.` components away, so `root/./x` is
    // deduplicated after all — measured while writing this test — while `..`
    // components are compared literally and survive. The premise is asserted
    // rather than assumed: if the interlock ever deduplicates canonically,
    // this arrangement stops producing the shape under test and the test
    // must fail here rather than pass vacuously.
    let request = Request {
        profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
        token: Some(sandbox.manifest.token().to_owned()),
        targets: vec![
            sandbox.root.join("gpt-basic-512.img"),
            sandbox
                .root
                .join("..")
                .join(sandbox.root.file_name().expect("sandbox root has a name"))
                .join("gpt-basic-512.img"),
        ],
    };
    let authorization = authorize(&sandbox.root, &request).expect("both spellings verify on unix");
    assert_eq!(
        authorization.targets().len(),
        2,
        "the premise: two verified handles reached admission"
    );
    let refusal = Admission::admit(&FAKE_SUITE, authorization)
        .expect_err("two handles for one declared fixture must refuse");
    assert_eq!(
        refusal,
        Refusal::DuplicateAuthorizedTarget {
            suite: "test-only-fake-suite",
            target: "gpt-basic-512.img".to_owned(),
            count: 2
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   On Windows two spellings of one fixture cannot both verify: the target share mode refuses the second open upstream, so no duplicate-handle authorization can reach admission there.
// Evidence: a_second_handle_to_one_fixture_refuses_upstream_on_windows
#[cfg(windows)]
#[test]
fn a_second_handle_to_one_fixture_refuses_upstream_on_windows() {
    // The unix half of this pair proves admission itself counts handles.
    // That shape is unreachable on Windows — the first verified handle's
    // share mode refuses the second write-capable open — which this pins, so
    // the platform split in the sibling test stays a recorded fact rather
    // than an assumption.
    let sandbox = Sandbox::new("duphandles");
    // The `..` spelling, not `./`: `Path` equality normalizes `.` away, so
    // that spelling is deduplicated upstream and never reaches the open.
    let request = Request {
        profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
        token: Some(sandbox.manifest.token().to_owned()),
        targets: vec![
            sandbox.root.join("gpt-basic-512.img"),
            sandbox
                .root
                .join("..")
                .join(sandbox.root.file_name().expect("sandbox root has a name"))
                .join("gpt-basic-512.img"),
        ],
    };
    let refusal = authorize(&sandbox.root, &request)
        .expect_err("the second open of one object must refuse on windows");
    assert!(
        matches!(
            refusal,
            crate::interlock::Refusal::TargetUnresolvable { .. }
        ),
        "wrong refusal: {refusal}"
    );
}

// Requirements: SAFE-007, SAFE-005
//   An authorization missing a declared fixture is refused: the contract's digest bracket cannot be established over objects that are not there.
// Evidence: a_missing_declared_fixture_is_refused
#[test]
fn a_missing_declared_fixture_is_refused() {
    let sandbox = Sandbox::new("missing");
    let authorization = sandbox.authorization(&["blank-512.img"]);
    let refusal = Admission::admit(&FAKE_SUITE, authorization)
        .expect_err("a missing declared fixture must refuse");
    match refusal {
        Refusal::TargetsNotTheDeclaredSet { missing, extra, .. } => {
            assert_eq!(missing, ["gpt-basic-512.img"]);
            assert_eq!(extra, ["blank-512.img"]);
        }
        other => panic!("wrong refusal: {other}"),
    }
}

// Requirements: SAFE-007, SAFE-005
//   A suite declaring no fixtures is refused rather than vacuously admitted.
// Evidence: a_suite_addressing_nothing_is_refused
#[test]
fn a_suite_addressing_nothing_is_refused() {
    let sandbox = Sandbox::new("nothing");
    let suite = Box::leak(Box::new(suite_with(&[])));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an empty fixture set must refuse");
    assert_eq!(
        refusal,
        Refusal::SuiteAddressesNothing {
            suite: "test-only-fake-suite"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A contract permitting no change is refused: a suite that changes nothing must not carry the destructive profile.
// Evidence: a_contract_permitting_no_change_is_refused
#[test]
fn a_contract_permitting_no_change_is_refused() {
    let sandbox = Sandbox::new("nochange");
    let suite = Box::leak(Box::new(suite_with(&NO_CHANGE)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a vacuous contract must refuse");
    assert_eq!(
        refusal,
        Refusal::ContractPermitsNoChange {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A zero-length declared range is refused: it permits nothing and reads as if it permits something.
// Evidence: a_zero_length_range_is_refused
#[test]
fn a_zero_length_range_is_refused() {
    let sandbox = Sandbox::new("zerolen");
    let suite = Box::leak(Box::new(suite_with(&ZERO_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a zero-length range must refuse");
    assert_eq!(
        refusal,
        Refusal::EmptyRange {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img",
            offset: 512
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A range past the generated length is refused, including on addition overflow.
// Evidence: a_range_past_the_generated_length_is_refused
#[test]
fn a_range_past_the_generated_length_is_refused() {
    let sandbox = Sandbox::new("oob");
    let suite = Box::leak(Box::new(suite_with(&PAST_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an out-of-bounds range must refuse");
    assert!(matches!(refusal, Refusal::RangeOutOfBounds { .. }));

    // The overflow shape refuses the same way rather than wrapping.
    let overflow_suite = Box::leak(Box::new(suite_with(&OVERFLOW_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal = Admission::admit(overflow_suite, authorization)
        .expect_err("an overflowing range must refuse");
    assert!(matches!(refusal, Refusal::RangeOutOfBounds { .. }));
}

// Requirements: SAFE-007, SAFE-005
//   Overlapping declared ranges are refused; touching ranges are not, and the boundary byte is the test.
// Evidence: overlapping_ranges_are_refused_and_touching_ranges_are_not
#[test]
fn overlapping_ranges_are_refused_and_touching_ranges_are_not() {
    let sandbox = Sandbox::new("overlap");
    let suite = Box::leak(Box::new(suite_with(&OVERLAP_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("overlapping ranges must refuse");
    assert_eq!(
        refusal,
        Refusal::RangesOverlap {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );

    let touching_suite = Box::leak(Box::new(suite_with(&TOUCHING_CONTRACT)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    Admission::admit(touching_suite, authorization).expect("touching ranges are admitted");
}

// Requirements: SAFE-007, SAFE-005
//   A duplicate fixture contract is refused as ambiguous.
// Evidence: a_duplicate_fixture_contract_is_refused
#[test]
fn a_duplicate_fixture_contract_is_refused() {
    let sandbox = Sandbox::new("dup");
    let suite = Box::leak(Box::new(suite_with(&DUP)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("a duplicate contract must refuse");
    assert_eq!(
        refusal,
        Refusal::DuplicateFixtureContract {
            suite: "test-only-fake-suite",
            fixture: "gpt-basic-512.img"
        }
    );
}

// Requirements: SAFE-007, SAFE-005
//   A contract naming a fixture the catalogue does not generate is refused, so a contract cannot outlive its fixture.
// Evidence: a_contract_over_a_withdrawn_fixture_is_refused
#[test]
fn a_contract_over_a_withdrawn_fixture_is_refused() {
    let sandbox = Sandbox::new("withdrawn");
    let suite = Box::leak(Box::new(suite_with(&GONE)));
    let authorization = sandbox.authorization(&["gpt-basic-512.img"]);
    let refusal =
        Admission::admit(suite, authorization).expect_err("an unknown fixture must refuse");
    assert_eq!(
        refusal,
        Refusal::NotAGeneratedFixture {
            suite: "test-only-fake-suite",
            fixture: "never-generated.img"
        }
    );
}

// Requirements: SAFE-007
//   Admission is unreachable without every interlock factor: its signature consumes the authorization the factors produce, so a missing factor refuses upstream and no admission can exist.
// Evidence: a_suite_cannot_be_admitted_without_every_interlock_factor
#[test]
fn a_suite_cannot_be_admitted_without_every_interlock_factor() {
    // The registry adds a condition; it must never substitute for one. The
    // only constructor consumes an `Authorization`, so the demonstration is
    // that the authorization itself refuses — there is no admission code
    // path that could run after this, by type rather than by discipline.
    let sandbox = Sandbox::new("factors");
    let request = Request {
        profile: Some(DESTRUCTIVE_PROFILE.to_owned()),
        token: None,
        targets: vec![sandbox.root.join("gpt-basic-512.img")],
    };
    authorize(&sandbox.root, &request).expect_err("a missing token must refuse upstream");
}

// Requirements: SAFE-007
//   The target-class and teardown vocabularies are closed: an exhaustive match pins every variant, so a new one fails compilation here as a visible reviewed edit.
// Evidence: the_registry_vocabularies_are_closed
#[test]
fn the_registry_vocabularies_are_closed() {
    // No wildcard arms. Adding a variant to either enum breaks this build
    // until the addition is reviewed here, which is the point.
    fn name_class(class: TargetClass) -> &'static str {
        match class {
            TargetClass::GeneratedFixtureFile => "generated-fixture-file",
        }
    }
    fn name_obligation(obligation: TeardownObligation) -> &'static str {
        match obligation {
            TeardownObligation::ChangedExactlyAsContracted => "changed-exactly-as-contracted",
            TeardownObligation::UnchangedOutsideContract => "unchanged-outside-contract",
            TeardownObligation::DetachConfirmed => "detach-confirmed",
            TeardownObligation::BackingRegeneratedToCatalogue => "backing-regenerated-to-catalogue",
        }
    }
    assert_eq!(
        name_class(FAKE_SUITE.target_class),
        "generated-fixture-file"
    );
    assert_eq!(FAKE_SUITE.teardown.len(), 4);
    for obligation in FAKE_SUITE.teardown {
        assert!(!name_obligation(*obligation).is_empty());
    }
}
