//! Deterministic Slint source generated from the renderer-neutral token set.
//!
//! This module deliberately has no Slint dependency. It produces the committed
//! typed boundary and style wrappers that the exactly pinned compiler adapter
//! compiles and inspects. A clean generation proves byte reproducibility and
//! complete static vocabulary transfer; it does not prove that a renderer
//! paints the declared values.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::{self, Write as _};
use std::path::PathBuf;

use crate::audit;
use crate::color::Srgb;
use crate::tokens::{
    CursorKind, FontFamilyStrategy, HorizontalAlignment, Pairing, TextFlow, TextOverflow,
    TextStyle, TextWrap, ThemeId, TokenSet, VerticalAlignment,
};

/// Repository-relative path of the committed generated Slint contract.
pub const GENERATED_SLINT_PATH: &str = "packages/design-tokens/generated/partman-tokens.slint";

/// Why an audited token set could not be rendered as the generated contract.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GenerationError {
    /// Independent token policy rejected the input before generation began.
    Audit(String),
    /// A value required after the audit was unexpectedly absent.
    Missing {
        /// Kind of value being resolved.
        kind: &'static str,
        /// Canonical identifier that was absent.
        id: String,
    },
    /// Two source identifiers would have the same generated language name.
    IdentifierCollision {
        /// Generated enum or member namespace.
        namespace: String,
        /// Colliding generated name.
        generated: String,
    },
    /// A closed schema spelling had no Slint representation.
    Unsupported {
        /// Kind of value that could not be represented.
        kind: &'static str,
        /// Unsupported schema spelling.
        value: String,
    },
}

impl fmt::Display for GenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Audit(summary) => write!(
                formatter,
                "refusing to generate Slint from a token set that failed its independent audit:\n{summary}"
            ),
            Self::Missing { kind, id } => {
                write!(formatter, "audited token set is missing {kind} {id:?}")
            }
            Self::IdentifierCollision {
                namespace,
                generated,
            } => write!(
                formatter,
                "generated Slint namespace {namespace:?} contains duplicate name {generated:?}"
            ),
            Self::Unsupported { kind, value } => {
                write!(formatter, "unsupported {kind} spelling {value:?}")
            }
        }
    }
}

impl std::error::Error for GenerationError {}

/// Absolute path of the committed generated Slint contract.
#[must_use]
pub fn repository_generated_slint_path() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let _crate_directory = path.pop();
    let _crates_directory = path.pop();
    path.push(GENERATED_SLINT_PATH);
    path
}

/// Render the audited token set as deterministic Slint source.
///
/// The output uses UTF-8, LF line endings, no byte-order mark, and exactly one
/// final newline. Maps are already held in [`BTreeMap`]s and therefore render
/// in Unicode scalar-value order independent of JSON member order. Schema
/// arrays retain their declared order.
///
/// # Errors
///
/// Returns [`GenerationError::Audit`] unless the independent policy audit is
/// clean. It also fails closed if an audited relationship is unexpectedly
/// absent, if a closed spelling lacks a Slint mapping, or if language-name
/// normalization would cause a collision.
pub fn render(set: &TokenSet) -> Result<String, GenerationError> {
    let report = audit(set);
    if !report.is_clean() {
        return Err(GenerationError::Audit(report.summary()));
    }

    let inventory = Inventory::new(set)?;
    inventory.check_identifiers()?;

    let mut output = String::new();
    output.push_str(
        "// @generated by partman-tokens from schemas/design-tokens.json.\n\
         // DO NOT EDIT. Run `cargo run -p partman-tokens --bin generate_slint_tokens -- --write`.\n\
         // This interface remains subject to separate compiler and rendered qualification.\n\n\
         import { Palette } from \"std-widgets.slint\";\n\n",
    );

    emit_enums(&mut output, &inventory);
    emit_theme_adapter(&mut output, &inventory);
    emit_structs(&mut output);
    emit_inventory_global(&mut output, &inventory);
    emit_raw_palette_global(&mut output, &inventory)?;
    emit_metrics_global(&mut output, &inventory)?;
    emit_contrast_global(&mut output, &inventory)?;
    emit_style_wrappers(&mut output);

    debug_assert!(!output.contains('\r'));
    debug_assert!(output.ends_with('\n'));
    debug_assert!(!output.ends_with("\n\n"));
    Ok(output)
}

struct Inventory<'a> {
    set: &'a TokenSet,
    themes: Vec<&'a str>,
    color_roles: Vec<&'a str>,
    semantic_roles: Vec<&'a str>,
    marks: Vec<&'a str>,
    shapes: Vec<&'a str>,
    label_ids: Vec<&'a str>,
    text_pairs: Vec<&'a Pairing>,
    ui_pairs: Vec<&'a Pairing>,
}

impl<'a> Inventory<'a> {
    fn new(set: &'a TokenSet) -> Result<Self, GenerationError> {
        let themes = set.themes.keys().map(String::as_str).collect::<Vec<_>>();
        let reference_theme = set
            .themes
            .get("dark")
            .ok_or_else(|| missing("theme", "dark"))?;
        let color_roles = reference_theme
            .colors
            .keys()
            .map(String::as_str)
            .collect::<Vec<_>>();
        let semantic_roles = set
            .non_color_channels
            .roles
            .keys()
            .map(String::as_str)
            .collect::<Vec<_>>();
        let marks = set
            .non_color_channels
            .roles
            .values()
            .map(|channels| channels.icon.as_str())
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect::<Vec<_>>();
        let shapes = set
            .non_color_channels
            .roles
            .values()
            .map(|channels| channels.shape.as_str())
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect::<Vec<_>>();
        let label_ids = set
            .themes
            .values()
            .map(|theme| theme.label_id.as_str())
            .chain(std::iter::once(
                set.theme_signals.system_selection_label_id.as_str(),
            ))
            .chain(
                set.non_color_channels
                    .roles
                    .values()
                    .map(|channels| channels.label_id.as_str()),
            )
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect::<Vec<_>>();

        let mut text_pairs = Vec::new();
        let mut ui_pairs = Vec::new();
        for pairing in &set.contrast_rules.pairings {
            match pairing.kind.as_str() {
                "text" => text_pairs.push(pairing),
                "ui" => ui_pairs.push(pairing),
                other => {
                    return Err(GenerationError::Unsupported {
                        kind: "contrast kind",
                        value: other.to_owned(),
                    });
                }
            }
        }

        Ok(Self {
            set,
            themes,
            color_roles,
            semantic_roles,
            marks,
            shapes,
            label_ids,
            text_pairs,
            ui_pairs,
        })
    }

    fn check_identifiers(&self) -> Result<(), GenerationError> {
        Self::check_namespace(
            "PartmanMeasurementUnit",
            [
                self.set.measurement_units.px.as_str(),
                self.set.measurement_units.letter_spacing_milli_px.as_str(),
                self.set.measurement_units.line_height_permille.as_str(),
            ]
            .into_iter(),
        )?;
        Self::check_namespace("PartmanThemeId", self.themes.iter().copied())?;
        Self::check_namespace("PartmanColorRole", self.color_roles.iter().copied())?;
        Self::check_namespace("PartmanSemanticRole", self.semantic_roles.iter().copied())?;
        Self::check_namespace("PartmanMarkId", self.marks.iter().copied())?;
        Self::check_namespace("PartmanShapeId", self.shapes.iter().copied())?;
        Self::check_namespace("PartmanLabelId", self.label_ids.iter().copied())?;
        Self::check_namespace(
            "PartmanFontFamilyId",
            self.set.typography.families.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanFontFamilyStrategy",
            ["platform-default"].into_iter(),
        )?;
        Self::check_namespace(
            "PartmanTextStyleId",
            self.set.typography.styles.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanTextFlowId",
            self.set.typography.flows.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanSpacingId",
            self.set.layout.spacing_px.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanRadiusId",
            self.set.layout.radius_px.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanStrokeId",
            self.set.layout.stroke_px.keys().map(String::as_str),
        )?;
        Self::check_namespace(
            "PartmanCursorRoleId",
            self.set.cursors.roles.keys().map(String::as_str),
        )?;
        Self::check_pair_namespace("PartmanTextContrastPairId", &self.text_pairs)?;
        Self::check_pair_namespace("PartmanUiContrastPairId", &self.ui_pairs)?;
        Ok(())
    }

    fn check_namespace(
        namespace: &str,
        values: impl Iterator<Item = &'a str>,
    ) -> Result<(), GenerationError> {
        let mut slint_names = BTreeSet::new();
        let mut rust_names = BTreeSet::new();
        for value in values {
            let variant = encoded_variant(value);
            if !slint_names.insert(variant.clone()) {
                return Err(identifier_collision(namespace, variant));
            }
            let rust_name = slint_pascal_case(&variant);
            if !rust_names.insert(rust_name.clone()) {
                return Err(identifier_collision(namespace, rust_name));
            }
        }
        Ok(())
    }

    fn check_pair_namespace(namespace: &str, pairs: &[&Pairing]) -> Result<(), GenerationError> {
        let mut slint_names = BTreeSet::new();
        let mut rust_names = BTreeSet::new();
        for pair in pairs {
            let variant = pair_variant(&pair.foreground, &pair.background);
            if !slint_names.insert(variant.clone()) {
                return Err(identifier_collision(namespace, variant));
            }
            let rust_name = slint_pascal_case(&variant);
            if !rust_names.insert(rust_name.clone()) {
                return Err(identifier_collision(namespace, rust_name));
            }
        }
        Ok(())
    }
}

fn missing(kind: &'static str, id: impl Into<String>) -> GenerationError {
    GenerationError::Missing {
        kind,
        id: id.into(),
    }
}

fn identifier_collision(namespace: &str, generated: String) -> GenerationError {
    GenerationError::IdentifierCollision {
        namespace: namespace.to_owned(),
        generated,
    }
}

/// Encode a data-derived identifier as a reversible, keyword-proof Slint name.
///
/// Raw `z` is escaped so `zHH` has exactly one interpretation. The output is
/// ASCII alphanumeric, begins with `v`, and is unaffected by Slint's underscore
/// to hyphen normalization.
fn encoded_variant(source: &str) -> String {
    let mut output = String::with_capacity(source.len() + 1);
    output.push('v');
    for byte in source.as_bytes() {
        if matches!(*byte, b'a'..=b'y' | b'0'..=b'9') {
            output.push(char::from(*byte));
        } else {
            write!(output, "z{byte:02x}").expect("writing to String cannot fail");
        }
    }
    output
}

fn pair_variant(foreground: &str, background: &str) -> String {
    format!(
        "{}-to-{}",
        encoded_variant(foreground),
        encoded_variant(background)
    )
}

/// Mirror Slint 1.17.1's Rust-code-generator enum collision transform.
fn slint_pascal_case(source: &str) -> String {
    let mut output = Vec::with_capacity(source.len());
    let mut next_upper = true;
    for byte in source.bytes() {
        if byte == b'-' {
            next_upper = true;
        } else if next_upper {
            output.push(byte.to_ascii_uppercase());
            next_upper = false;
        } else {
            output.push(byte);
        }
    }
    String::from_utf8(output).expect("encoded Slint identifiers are ASCII")
}

fn emit_enums(output: &mut String, inventory: &Inventory<'_>) {
    emit_enum(
        output,
        "PartmanMeasurementUnit",
        [
            inventory.set.measurement_units.px.as_str(),
            inventory
                .set
                .measurement_units
                .letter_spacing_milli_px
                .as_str(),
            inventory
                .set
                .measurement_units
                .line_height_permille
                .as_str(),
        ],
    );
    emit_enum(output, "PartmanThemeId", inventory.themes.iter().copied());
    emit_enum(
        output,
        "PartmanColorRole",
        inventory.color_roles.iter().copied(),
    );
    emit_enum(
        output,
        "PartmanSemanticRole",
        inventory.semantic_roles.iter().copied(),
    );
    emit_enum(output, "PartmanMarkId", inventory.marks.iter().copied());
    emit_enum(output, "PartmanShapeId", inventory.shapes.iter().copied());
    emit_enum(
        output,
        "PartmanLabelId",
        inventory.label_ids.iter().copied(),
    );
    emit_enum(
        output,
        "PartmanFontFamilyId",
        inventory.set.typography.families.keys().map(String::as_str),
    );
    emit_enum(output, "PartmanFontFamilyStrategy", ["platform-default"]);
    emit_enum(
        output,
        "PartmanTextStyleId",
        inventory.set.typography.styles.keys().map(String::as_str),
    );
    emit_enum(
        output,
        "PartmanTextFlowId",
        inventory.set.typography.flows.keys().map(String::as_str),
    );
    emit_enum(
        output,
        "PartmanSpacingId",
        inventory.set.layout.spacing_px.keys().map(String::as_str),
    );
    emit_enum(
        output,
        "PartmanRadiusId",
        inventory.set.layout.radius_px.keys().map(String::as_str),
    );
    emit_enum(
        output,
        "PartmanStrokeId",
        inventory.set.layout.stroke_px.keys().map(String::as_str),
    );
    emit_enum(
        output,
        "PartmanCursorRoleId",
        inventory.set.cursors.roles.keys().map(String::as_str),
    );
    emit_pair_enum(output, "PartmanTextContrastPairId", &inventory.text_pairs);
    emit_pair_enum(output, "PartmanUiContrastPairId", &inventory.ui_pairs);
}

fn emit_theme_adapter(output: &mut String, inventory: &Inventory<'_>) {
    let signals = &inventory.set.theme_signals;
    writeln!(
        output,
        "export global PartmanGeneratedThemeAdapter {{\n    // G-CFG-05's sole upstream style read: no Palette brush crosses this adapter.\n    out property <PartmanThemeId> system-theme: Palette.color-scheme == ColorScheme.light\n        ? PartmanThemeId.{}\n        : (Palette.color-scheme == ColorScheme.dark\n            ? PartmanThemeId.{}\n            : PartmanThemeId.{});\n}}\n",
        encoded_variant(theme_id(signals.system_color_scheme.light)),
        encoded_variant(theme_id(signals.system_color_scheme.dark)),
        encoded_variant(theme_id(signals.system_color_scheme.unknown)),
    )
    .expect("writing to String cannot fail");
}

fn emit_enum<'a>(output: &mut String, name: &str, values: impl IntoIterator<Item = &'a str>) {
    writeln!(output, "export enum {name} {{").expect("writing to String cannot fail");
    for value in values {
        writeln!(output, "    {},", encoded_variant(value)).expect("writing to String cannot fail");
    }
    output.push_str("}\n\n");
}

fn emit_pair_enum(output: &mut String, name: &str, pairs: &[&Pairing]) {
    writeln!(output, "export enum {name} {{").expect("writing to String cannot fail");
    for pair in pairs {
        writeln!(
            output,
            "    {},",
            pair_variant(&pair.foreground, &pair.background)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("}\n\n");
}

fn emit_structs(output: &mut String) {
    output.push_str(
        "export struct PartmanMeasurementUnits {\n\
         \x20   pixels: PartmanMeasurementUnit,\n\
         \x20   letter-spacing: PartmanMeasurementUnit,\n\
         \x20   line-height: PartmanMeasurementUnit,\n\
         }\n\n\
         export struct PartmanThemeSpec {\n\
         \x20   id: PartmanThemeId,\n\
         \x20   label-id: PartmanLabelId,\n\
         }\n\n\
         export struct PartmanThemeSignals {\n\
         \x20   default-theme: PartmanThemeId,\n\
         \x20   system-selection-label-id: PartmanLabelId,\n\
         \x20   unknown-color-scheme-theme: PartmanThemeId,\n\
         \x20   dark-color-scheme-theme: PartmanThemeId,\n\
         \x20   light-color-scheme-theme: PartmanThemeId,\n\
         \x20   high-contrast-theme: PartmanThemeId,\n\
         }\n\n\
         export struct PartmanSemanticChannels {\n\
         \x20   role: PartmanSemanticRole,\n\
         \x20   color-role: PartmanColorRole,\n\
         \x20   mark: PartmanMarkId,\n\
         \x20   shape: PartmanShapeId,\n\
         \x20   label-id: PartmanLabelId,\n\
         }\n\n\
         export struct PartmanFontFamilySpec {\n\
         \x20   id: PartmanFontFamilyId,\n\
         \x20   strategy: PartmanFontFamilyStrategy,\n\
         }\n\n\
         export struct PartmanTextStyleSpec {\n\
         \x20   id: PartmanTextStyleId,\n\
         \x20   family: PartmanFontFamilyId,\n\
         \x20   font-size: length,\n\
         \x20   font-weight: int,\n\
         \x20   font-italic: bool,\n\
         \x20   letter-spacing: length,\n\
         \x20   line-height-permille: int,\n\
         }\n\n\
         export struct PartmanTextFlowSpec {\n\
         \x20   id: PartmanTextFlowId,\n\
         \x20   wrap: TextWrap,\n\
         \x20   overflow: TextOverflow,\n\
         \x20   horizontal-alignment: TextHorizontalAlignment,\n\
         \x20   vertical-alignment: TextVerticalAlignment,\n\
         }\n\n\
         export struct PartmanTextContrastPair {\n\
         \x20   id: PartmanTextContrastPairId,\n\
         \x20   foreground: PartmanColorRole,\n\
         \x20   background: PartmanColorRole,\n\
         }\n\n\
         export struct PartmanUiContrastPair {\n\
         \x20   id: PartmanUiContrastPairId,\n\
         \x20   foreground: PartmanColorRole,\n\
         \x20   background: PartmanColorRole,\n\
         }\n\n\
         export struct PartmanTextContrastColors {\n\
         \x20   foreground: color,\n\
         \x20   background: color,\n\
         }\n\n\
         export struct PartmanUiContrastColors {\n\
         \x20   foreground: color,\n\
         \x20   background: color,\n\
         }\n\n\
         export struct PartmanTextInputSpec {\n\
         \x20   style: PartmanTextStyleId,\n\
         \x20   flow: PartmanTextFlowId,\n\
         \x20   selection-pair: PartmanTextContrastPairId,\n\
         }\n\n\
         export struct PartmanLayoutSpec {\n\
         \x20   default-layout-padding: PartmanSpacingId,\n\
         \x20   default-layout-spacing: PartmanSpacingId,\n\
         \x20   focus-ring-offset: length,\n\
         \x20   minimum-target-size: length,\n\
         }\n\n\
         export struct PartmanCursorSpec {\n\
         \x20   role: PartmanCursorRoleId,\n\
         \x20   cursor: MouseCursor,\n\
         }\n\n\
         export struct PartmanDistinctRolePair {\n\
         \x20   first: PartmanColorRole,\n\
         \x20   second: PartmanColorRole,\n\
         }\n\n",
    );
}

fn emit_inventory_global(output: &mut String, inventory: &Inventory<'_>) {
    output.push_str("export global PartmanTokenInventory {\n");
    writeln!(
        output,
        "    out property <string> token-set-version: \"{}\";",
        inventory.set.token_set_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    out property <string> spec-version: \"{}\";",
        inventory.set.spec_version
    )
    .expect("writing to String cannot fail");

    output.push_str("    out property <[PartmanThemeSpec]> themes: [\n");
    for (name, theme) in &inventory.set.themes {
        writeln!(
            output,
            "        {{ id: PartmanThemeId.{}, label-id: PartmanLabelId.{} }},",
            encoded_variant(name),
            encoded_variant(&theme.label_id)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
    emit_id_model(
        output,
        "PartmanColorRole",
        "color-roles",
        inventory.color_roles.iter().copied(),
    );
    emit_id_model(
        output,
        "PartmanMarkId",
        "marks",
        inventory.marks.iter().copied(),
    );
    emit_id_model(
        output,
        "PartmanShapeId",
        "shapes",
        inventory.shapes.iter().copied(),
    );
    emit_id_model(
        output,
        "PartmanLabelId",
        "label-ids",
        inventory.label_ids.iter().copied(),
    );

    output.push_str("    out property <[PartmanSemanticChannels]> semantic-channels: [\n");
    for (role, channels) in &inventory.set.non_color_channels.roles {
        writeln!(
            output,
            "        {{ role: PartmanSemanticRole.{role_id}, color-role: PartmanColorRole.{role_id}, mark: PartmanMarkId.{mark}, shape: PartmanShapeId.{shape}, label-id: PartmanLabelId.{label} }},",
            role_id = encoded_variant(role),
            mark = encoded_variant(&channels.icon),
            shape = encoded_variant(&channels.shape),
            label = encoded_variant(&channels.label_id),
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");

    let signals = &inventory.set.theme_signals;
    writeln!(
        output,
        "    out property <PartmanThemeSignals> theme-signals: {{ default-theme: PartmanThemeId.{}, system-selection-label-id: PartmanLabelId.{}, unknown-color-scheme-theme: PartmanThemeId.{}, dark-color-scheme-theme: PartmanThemeId.{}, light-color-scheme-theme: PartmanThemeId.{}, high-contrast-theme: PartmanThemeId.{} }};",
        encoded_variant(theme_id(signals.default_theme)),
        encoded_variant(&signals.system_selection_label_id),
        encoded_variant(theme_id(signals.system_color_scheme.unknown)),
        encoded_variant(theme_id(signals.system_color_scheme.dark)),
        encoded_variant(theme_id(signals.system_color_scheme.light)),
        encoded_variant(theme_id(signals.high_contrast_theme)),
    )
    .expect("writing to String cannot fail");

    emit_pair_model(
        output,
        "PartmanTextContrastPair",
        "PartmanTextContrastPairId",
        "text-contrast-pairs",
        &inventory.text_pairs,
    );
    emit_pair_model(
        output,
        "PartmanUiContrastPair",
        "PartmanUiContrastPairId",
        "ui-contrast-pairs",
        &inventory.ui_pairs,
    );

    output.push_str("    out property <[PartmanDistinctRolePair]> must-remain-distinct: [\n");
    for [first, second] in &inventory.set.color_vision_separation.must_remain_distinct {
        writeln!(
            output,
            "        {{ first: PartmanColorRole.{}, second: PartmanColorRole.{} }},",
            encoded_variant(first),
            encoded_variant(second)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n}\n\n");
}

fn emit_id_model<'a>(
    output: &mut String,
    type_name: &str,
    property_name: &str,
    values: impl IntoIterator<Item = &'a str>,
) {
    writeln!(
        output,
        "    out property <[{type_name}]> {property_name}: ["
    )
    .expect("writing to String cannot fail");
    for value in values {
        writeln!(output, "        {type_name}.{},", encoded_variant(value))
            .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
}

fn emit_pair_model(
    output: &mut String,
    struct_name: &str,
    enum_name: &str,
    property_name: &str,
    pairs: &[&Pairing],
) {
    writeln!(
        output,
        "    out property <[{struct_name}]> {property_name}: ["
    )
    .expect("writing to String cannot fail");
    for pair in pairs {
        writeln!(
            output,
            "        {{ id: {enum_name}.{}, foreground: PartmanColorRole.{}, background: PartmanColorRole.{} }},",
            pair_variant(&pair.foreground, &pair.background),
            encoded_variant(&pair.foreground),
            encoded_variant(&pair.background),
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
}

fn emit_raw_palette_global(
    output: &mut String,
    inventory: &Inventory<'_>,
) -> Result<(), GenerationError> {
    output.push_str("export global PartmanRawGeneratedPalette {\n");
    for role in &inventory.color_roles {
        writeln!(
            output,
            "    public pure function color-{}(theme: PartmanThemeId) -> color {{",
            encoded_variant(role)
        )
        .expect("writing to String cannot fail");
        let (last_theme, preceding) = inventory
            .themes
            .split_last()
            .ok_or_else(|| missing("theme", "<any>"))?;
        for theme_name in preceding {
            let value = theme_color(inventory.set, theme_name, role)?;
            writeln!(
                output,
                "        if (theme == PartmanThemeId.{}) {{ return {}; }}",
                encoded_variant(theme_name),
                value
            )
            .expect("writing to String cannot fail");
        }
        let fallback = theme_color(inventory.set, last_theme, role)?;
        writeln!(
            output,
            "        // PartmanThemeId is exact; the final value is the remaining canonical theme.\n        return {fallback};"
        )
        .expect("writing to String cannot fail");
        output.push_str("    }\n");
    }
    output.push_str("}\n\n");
    Ok(())
}

fn theme_color(set: &TokenSet, theme: &str, role: &str) -> Result<String, GenerationError> {
    let value = set
        .themes
        .get(theme)
        .ok_or_else(|| missing("theme", theme))?
        .colors
        .get(role)
        .ok_or_else(|| missing("color role", format!("{theme}/{role}")))?;
    let color = Srgb::parse(value).map_err(|_| GenerationError::Unsupported {
        kind: "color",
        value: value.clone(),
    })?;
    Ok(format!("#{:02X}{:02X}{:02X}", color.r, color.g, color.b))
}

fn emit_metrics_global(
    output: &mut String,
    inventory: &Inventory<'_>,
) -> Result<(), GenerationError> {
    let set = inventory.set;
    output.push_str("export global PartmanGeneratedMetrics {\n");
    writeln!(
        output,
        "    out property <PartmanMeasurementUnits> measurement-units: {{ pixels: PartmanMeasurementUnit.{}, letter-spacing: PartmanMeasurementUnit.{}, line-height: PartmanMeasurementUnit.{} }};",
        encoded_variant(&set.measurement_units.px),
        encoded_variant(&set.measurement_units.letter_spacing_milli_px),
        encoded_variant(&set.measurement_units.line_height_permille),
    )
    .expect("writing to String cannot fail");

    output.push_str("    out property <[PartmanFontFamilySpec]> font-families: [\n");
    for (id, family) in &set.typography.families {
        writeln!(
            output,
            "        {{ id: PartmanFontFamilyId.{}, strategy: PartmanFontFamilyStrategy.{} }},",
            encoded_variant(id),
            encoded_variant(font_family_strategy(family.strategy)),
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");

    emit_text_style_model(output, &set.typography.styles);
    emit_text_flow_model(output, &set.typography.flows);
    emit_cursor_model(output, &set.cursors.roles);

    let selection = &set.typography.text_input.selection_pair;
    writeln!(
        output,
        "    out property <PartmanTextInputSpec> text-input: {{ style: PartmanTextStyleId.{}, flow: PartmanTextFlowId.{}, selection-pair: PartmanTextContrastPairId.{} }};",
        encoded_variant(&set.typography.text_input.style),
        encoded_variant(&set.typography.text_input.flow),
        pair_variant(&selection.foreground, &selection.background),
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    out property <PartmanLayoutSpec> layout: {{ default-layout-padding: PartmanSpacingId.{}, default-layout-spacing: PartmanSpacingId.{}, focus-ring-offset: {}px, minimum-target-size: {}px }};",
        encoded_variant(&set.layout.default_layout_padding),
        encoded_variant(&set.layout.default_layout_spacing),
        set.layout.focus_ring_offset_px,
        set.layout.minimum_target_size_px,
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    out property <length> text-caret-width: {}px;",
        set.cursors.text_caret_width_px
    )
    .expect("writing to String cannot fail");
    output.push_str(
        "    // An empty family delegates only the family name to Slint's platform default.\n\
         // Every generated text/window wrapper still binds the property explicitly.\n\
         out property <string> platform-font-family;\n",
    );

    emit_length_lookup(
        output,
        "spacing",
        "PartmanSpacingId",
        &set.layout.spacing_px,
    )?;
    emit_length_lookup(output, "radius", "PartmanRadiusId", &set.layout.radius_px)?;
    emit_length_lookup(output, "stroke", "PartmanStrokeId", &set.layout.stroke_px)?;
    emit_text_style_lookup(output, &set.typography.styles)?;
    emit_text_flow_lookup(output, &set.typography.flows)?;
    emit_cursor_lookup(output, &set.cursors.roles)?;
    output.push_str("}\n\n");
    Ok(())
}

fn emit_text_style_model(output: &mut String, styles: &BTreeMap<String, TextStyle>) {
    output.push_str("    out property <[PartmanTextStyleSpec]> text-styles: [\n");
    for (id, style) in styles {
        writeln!(output, "        {},", text_style_literal(id, style))
            .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
}

fn emit_text_flow_model(output: &mut String, flows: &BTreeMap<String, TextFlow>) {
    output.push_str("    out property <[PartmanTextFlowSpec]> text-flows: [\n");
    for (id, flow) in flows {
        writeln!(output, "        {},", text_flow_literal(id, flow))
            .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
}

fn emit_cursor_model(output: &mut String, cursors: &BTreeMap<String, CursorKind>) {
    output.push_str("    out property <[PartmanCursorSpec]> cursor-specs: [\n");
    for (role, cursor) in cursors {
        writeln!(
            output,
            "        {{ role: PartmanCursorRoleId.{}, cursor: MouseCursor.{} }},",
            encoded_variant(role),
            cursor_name(*cursor),
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("    ];\n");
}

fn emit_length_lookup(
    output: &mut String,
    function_name: &str,
    enum_name: &str,
    values: &BTreeMap<String, u16>,
) -> Result<(), GenerationError> {
    writeln!(
        output,
        "    public pure function {function_name}(id: {enum_name}) -> length {{"
    )
    .expect("writing to String cannot fail");
    let (last, preceding) = split_last_map(values, function_name)?;
    for (id, value) in preceding {
        writeln!(
            output,
            "        if (id == {enum_name}.{}) {{ return {value}px; }}",
            encoded_variant(id)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(output, "        return {}px;", last.1).expect("writing to String cannot fail");
    output.push_str("    }\n");
    Ok(())
}

fn emit_text_style_lookup(
    output: &mut String,
    styles: &BTreeMap<String, TextStyle>,
) -> Result<(), GenerationError> {
    output.push_str(
        "    public pure function text-style(id: PartmanTextStyleId) -> PartmanTextStyleSpec {\n",
    );
    let (last, preceding) = split_last_map(styles, "text style")?;
    for (id, style) in preceding {
        writeln!(
            output,
            "        if (id == PartmanTextStyleId.{}) {{ return {}; }}",
            encoded_variant(id),
            text_style_literal(id, style)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(
        output,
        "        return {};",
        text_style_literal(last.0, last.1)
    )
    .expect("writing to String cannot fail");
    output.push_str("    }\n");
    Ok(())
}

fn emit_text_flow_lookup(
    output: &mut String,
    flows: &BTreeMap<String, TextFlow>,
) -> Result<(), GenerationError> {
    output.push_str(
        "    public pure function text-flow(id: PartmanTextFlowId) -> PartmanTextFlowSpec {\n",
    );
    let (last, preceding) = split_last_map(flows, "text flow")?;
    for (id, flow) in preceding {
        writeln!(
            output,
            "        if (id == PartmanTextFlowId.{}) {{ return {}; }}",
            encoded_variant(id),
            text_flow_literal(id, flow)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(
        output,
        "        return {};",
        text_flow_literal(last.0, last.1)
    )
    .expect("writing to String cannot fail");
    output.push_str("    }\n");
    Ok(())
}

fn emit_cursor_lookup(
    output: &mut String,
    cursors: &BTreeMap<String, CursorKind>,
) -> Result<(), GenerationError> {
    output.push_str("    public pure function cursor(id: PartmanCursorRoleId) -> MouseCursor {\n");
    let (last, preceding) = split_last_map(cursors, "cursor")?;
    for (id, cursor) in preceding {
        writeln!(
            output,
            "        if (id == PartmanCursorRoleId.{}) {{ return MouseCursor.{}; }}",
            encoded_variant(id),
            cursor_name(*cursor)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(
        output,
        "        return MouseCursor.{};",
        cursor_name(*last.1)
    )
    .expect("writing to String cannot fail");
    output.push_str("    }\n");
    Ok(())
}

type LastAndPreceding<'a, T> = ((&'a str, &'a T), Vec<(&'a str, &'a T)>);

fn split_last_map<'a, T>(
    values: &'a BTreeMap<String, T>,
    kind: &str,
) -> Result<LastAndPreceding<'a, T>, GenerationError> {
    let mut entries = values
        .iter()
        .map(|(id, value)| (id.as_str(), value))
        .collect::<Vec<_>>();
    let last = entries.pop().ok_or_else(|| missing("lookup table", kind))?;
    Ok((last, entries))
}

fn text_style_literal(id: &str, style: &TextStyle) -> String {
    format!(
        "{{ id: PartmanTextStyleId.{}, family: PartmanFontFamilyId.{}, font-size: {}px, font-weight: {}, font-italic: {}, letter-spacing: {}, line-height-permille: {} }}",
        encoded_variant(id),
        encoded_variant(&style.family),
        style.size_px,
        style.weight,
        style.italic,
        milli_px(style.letter_spacing_milli_px),
        style.line_height_permille,
    )
}

fn text_flow_literal(id: &str, flow: &TextFlow) -> String {
    format!(
        "{{ id: PartmanTextFlowId.{}, wrap: TextWrap.{}, overflow: TextOverflow.{}, horizontal-alignment: TextHorizontalAlignment.{}, vertical-alignment: TextVerticalAlignment.{} }}",
        encoded_variant(id),
        text_wrap_name(flow.wrap),
        text_overflow_name(flow.overflow),
        horizontal_alignment_name(flow.horizontal_alignment),
        vertical_alignment_name(flow.vertical_alignment),
    )
}

fn milli_px(value: i16) -> String {
    let value = i32::from(value);
    let sign = if value < 0 { "-" } else { "" };
    let absolute = value.abs();
    let whole = absolute / 1_000;
    let remainder = absolute % 1_000;
    if remainder == 0 {
        format!("{sign}{whole}px")
    } else {
        let fraction = format!("{remainder:03}");
        format!("{sign}{whole}.{}px", fraction.trim_end_matches('0'))
    }
}

fn emit_contrast_global(
    output: &mut String,
    inventory: &Inventory<'_>,
) -> Result<(), GenerationError> {
    let text_threshold = inventory
        .set
        .contrast_rules
        .thresholds
        .get("text")
        .ok_or_else(|| missing("contrast threshold", "text"))?;
    let ui_threshold = inventory
        .set
        .contrast_rules
        .thresholds
        .get("ui")
        .ok_or_else(|| missing("contrast threshold", "ui"))?;
    output.push_str("export global PartmanGeneratedContrast {\n");
    writeln!(
        output,
        "    out property <float> text-minimum-contrast: {};",
        decimal(*text_threshold)
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    out property <float> ui-minimum-contrast: {};",
        decimal(*ui_threshold)
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    out property <float> minimum-delta-e: {};",
        decimal(inventory.set.color_vision_separation.minimum_delta_e)
    )
    .expect("writing to String cannot fail");
    emit_contrast_lookup(
        output,
        "text-colors",
        "PartmanTextContrastPairId",
        "PartmanTextContrastColors",
        &inventory.text_pairs,
    )?;
    emit_contrast_lookup(
        output,
        "ui-colors",
        "PartmanUiContrastPairId",
        "PartmanUiContrastColors",
        &inventory.ui_pairs,
    )?;
    output.push_str("}\n\n");
    Ok(())
}

fn emit_style_wrappers(output: &mut String) {
    output.push_str(
        r"// These wrappers are the only approved route to Slint's style-sensitive builtins.
// Their complete bindings prevent upstream style defaults from entering PartMan UI.
export component PartmanWindow inherits Window {
    in property <PartmanThemeId> theme: PartmanThemeId.vdark;
    in property <PartmanTextContrastPairId> surface-pair: PartmanTextContrastPairId.vtextz2eprimary-to-vsurfacez2ebase;

    background: PartmanGeneratedContrast.text-colors(root.theme, root.surface-pair).background;
    default-font-family: PartmanGeneratedMetrics.platform-font-family;
}

export component PartmanText inherits Text {
    in property <PartmanThemeId> theme: PartmanThemeId.vdark;
    in property <PartmanTextStyleId> style-id: PartmanTextStyleId.vbody;
    in property <PartmanTextFlowId> flow-id: PartmanTextFlowId.vmultiz2dline;
    in property <PartmanTextContrastPairId> contrast-pair: PartmanTextContrastPairId.vtextz2eprimary-to-vsurfacez2ebase;
    private property <PartmanTextStyleSpec> resolved-style: PartmanGeneratedMetrics.text-style(root.style-id);
    private property <PartmanTextFlowSpec> resolved-flow: PartmanGeneratedMetrics.text-flow(root.flow-id);

    color: PartmanGeneratedContrast.text-colors(root.theme, root.contrast-pair).foreground;
    font-family: PartmanGeneratedMetrics.platform-font-family;
    font-size: root.resolved-style.font-size;
    font-weight: root.resolved-style.font-weight;
    font-italic: root.resolved-style.font-italic;
    letter-spacing: root.resolved-style.letter-spacing;
    wrap: root.resolved-flow.wrap;
    overflow: root.resolved-flow.overflow;
    horizontal-alignment: root.resolved-flow.horizontal-alignment;
    vertical-alignment: root.resolved-flow.vertical-alignment;
}

export component PartmanStyledText inherits StyledText {
    in property <PartmanThemeId> theme: PartmanThemeId.vdark;
    in property <PartmanTextStyleId> style-id: PartmanTextStyleId.vbody;
    in property <PartmanTextFlowId> flow-id: PartmanTextFlowId.vmultiz2dline;
    in property <PartmanTextContrastPairId> contrast-pair: PartmanTextContrastPairId.vtextz2eprimary-to-vsurfacez2ebase;
    private property <PartmanTextStyleSpec> resolved-style: PartmanGeneratedMetrics.text-style(root.style-id);
    private property <PartmanTextFlowSpec> resolved-flow: PartmanGeneratedMetrics.text-flow(root.flow-id);

    default-color: PartmanGeneratedContrast.text-colors(root.theme, root.contrast-pair).foreground;
    default-font-family: PartmanGeneratedMetrics.platform-font-family;
    default-font-size: root.resolved-style.font-size;
    horizontal-alignment: root.resolved-flow.horizontal-alignment;
    vertical-alignment: root.resolved-flow.vertical-alignment;
}

export component PartmanTextInput inherits TextInput {
    in property <PartmanThemeId> theme: PartmanThemeId.vdark;
    in property <PartmanTextContrastPairId> contrast-pair: PartmanTextContrastPairId.vtextz2eprimary-to-vsurfacez2ebase;
    private property <PartmanTextStyleSpec> resolved-style: PartmanGeneratedMetrics.text-style(PartmanGeneratedMetrics.text-input.style);
    private property <PartmanTextFlowSpec> resolved-flow: PartmanGeneratedMetrics.text-flow(PartmanGeneratedMetrics.text-input.flow);
    private property <PartmanTextContrastColors> resolved-selection: PartmanGeneratedContrast.text-colors(root.theme, PartmanGeneratedMetrics.text-input.selection-pair);

    color: PartmanGeneratedContrast.text-colors(root.theme, root.contrast-pair).foreground;
    selection-background-color: root.resolved-selection.background;
    selection-foreground-color: root.resolved-selection.foreground;
    text-cursor-width: PartmanGeneratedMetrics.text-caret-width;
    font-family: PartmanGeneratedMetrics.platform-font-family;
    font-size: root.resolved-style.font-size;
    font-weight: root.resolved-style.font-weight;
    font-italic: root.resolved-style.font-italic;
    letter-spacing: root.resolved-style.letter-spacing;
    wrap: root.resolved-flow.wrap;
    horizontal-alignment: root.resolved-flow.horizontal-alignment;
    vertical-alignment: root.resolved-flow.vertical-alignment;
}

export component PartmanDialog inherits Dialog {
    in property <PartmanThemeId> theme: PartmanThemeId.vdark;
    in property <PartmanTextContrastPairId> surface-pair: PartmanTextContrastPairId.vtextz2eprimary-to-vsurfacez2ebase;
    private property <length> spacing: PartmanGeneratedMetrics.spacing(PartmanGeneratedMetrics.layout.default-layout-spacing);

    background: PartmanGeneratedContrast.text-colors(root.theme, root.surface-pair).background;
    default-font-family: PartmanGeneratedMetrics.platform-font-family;
    padding: PartmanGeneratedMetrics.spacing(PartmanGeneratedMetrics.layout.default-layout-padding);
}
",
    );
}

fn emit_contrast_lookup(
    output: &mut String,
    function_name: &str,
    enum_name: &str,
    result_name: &str,
    pairs: &[&Pairing],
) -> Result<(), GenerationError> {
    writeln!(
        output,
        "    public pure function {function_name}(theme: PartmanThemeId, pair: {enum_name}) -> {result_name} {{"
    )
    .expect("writing to String cannot fail");
    let (last, preceding) = pairs
        .split_last()
        .ok_or_else(|| missing("contrast pair", function_name))?;
    for pair in preceding {
        writeln!(
            output,
            "        if (pair == {enum_name}.{}) {{ return {}; }}",
            pair_variant(&pair.foreground, &pair.background),
            contrast_color_literal(pair)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(output, "        return {};", contrast_color_literal(last))
        .expect("writing to String cannot fail");
    output.push_str("    }\n");
    Ok(())
}

fn contrast_color_literal(pair: &Pairing) -> String {
    format!(
        "{{ foreground: PartmanRawGeneratedPalette.color-{}(theme), background: PartmanRawGeneratedPalette.color-{}(theme) }}",
        encoded_variant(&pair.foreground),
        encoded_variant(&pair.background),
    )
}

fn decimal(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}

const fn theme_id(value: ThemeId) -> &'static str {
    match value {
        ThemeId::Dark => "dark",
        ThemeId::HighContrast => "high-contrast",
        ThemeId::Light => "light",
    }
}

const fn font_family_strategy(value: FontFamilyStrategy) -> &'static str {
    match value {
        FontFamilyStrategy::PlatformDefault => "platform-default",
    }
}

const fn text_wrap_name(value: TextWrap) -> &'static str {
    match value {
        TextWrap::NoWrap => "no-wrap",
        TextWrap::WordWrap => "word-wrap",
    }
}

const fn text_overflow_name(value: TextOverflow) -> &'static str {
    match value {
        TextOverflow::Elide => "elide",
        TextOverflow::Clip => "clip",
    }
}

const fn horizontal_alignment_name(value: HorizontalAlignment) -> &'static str {
    match value {
        HorizontalAlignment::Left => "left",
    }
}

const fn vertical_alignment_name(value: VerticalAlignment) -> &'static str {
    match value {
        VerticalAlignment::Center => "center",
        VerticalAlignment::Top => "top",
    }
}

const fn cursor_name(value: CursorKind) -> &'static str {
    match value {
        CursorKind::Default => "default",
        CursorKind::Pointer => "pointer",
        CursorKind::NotAllowed => "not-allowed",
        CursorKind::Text => "text",
    }
}

#[cfg(test)]
mod tests;
